// METR-Horizon-v1.1 per-model time horizons and doubling-time fits, in
// minutes of human task time. Generated by tools/figure-data/metr-horizon.py;
// do not edit by hand.
//
// Source: https://metr.org/assets/benchmark_results_1_1.yaml
// Retrieved 2026-09-24; sha256 aae31902b0519a4da73e16643915e5e8aca13cd3315c3aac893ce3d6dfe92ad9;
// long_tasks_version 799cc9c4b4483a93fc3445623a49ea1bd74fdeb2.

export const SOURCE = {
  benchmark: "METR-Horizon-v1.1",
  url: "https://metr.org/assets/benchmark_results_1_1.yaml",
  retrieved: "2026-09-24",
} as const;

// The file's own fits, in days: all history (the stitched series) and models
// released from 2023 on. Both exclude central 50% estimates above 16 hours.
export const DOUBLING_DAYS = {
  all: 187.778,
  from2023: 128.744,
  from2023Interval: [104.428, 158.012],
} as const;

export const CEILING_MIN = 960;

export interface HorizonModel {
  id: string;
  name: string;
  released: string; // release date, YYYY-MM-DD
  frontier: boolean; // METR's is_sota flag: the frontier model at release
  originalSuite: boolean; // estimate from the original suite, not re-run on v1.1
  p50: readonly [number, number, number]; // estimate, interval low, interval high
  p80: readonly [number, number, number];
}

export const MODELS: readonly HorizonModel[] = [
  { id: "gpt2", name: "GPT-2", released: "2019-02-14", frontier: true, originalSuite: true, p50: [0.053778, 0.009994, 0.141825], p80: [0.0128, 0.001589, 0.068612] },
  { id: "davinci_002", name: "GPT-3 (davinci-002)", released: "2020-05-28", frontier: true, originalSuite: true, p50: [0.144057, 0.093319, 0.221209], p80: [0.056238, 0.034813, 0.105813] },
  { id: "gpt_3_5_turbo_instruct", name: "GPT-3.5 Turbo Instruct", released: "2022-03-15", frontier: true, originalSuite: true, p50: [0.599247, 0.255148, 1.115905], p80: [0.25538, 0.141649, 0.492933] },
  { id: "gpt_4", name: "GPT-4", released: "2023-03-14", frontier: true, originalSuite: false, p50: [3.987428, 1.93292, 7.995283], p80: [0.889561, 0.342984, 2.523746] },
  { id: "gpt_4_1106_inspect", name: "GPT-4 1106", released: "2023-11-06", frontier: true, originalSuite: false, p50: [4.044959, 1.866859, 8.443226], p80: [0.783032, 0.276599, 2.358414] },
  { id: "claude_3_opus_inspect", name: "Claude 3 Opus", released: "2024-03-04", frontier: false, originalSuite: false, p50: [3.952262, 1.706313, 8.76484], p80: [0.638973, 0.190491, 2.118276] },
  { id: "gpt_4_turbo_inspect", name: "GPT-4 Turbo", released: "2024-04-09", frontier: false, originalSuite: false, p50: [3.732787, 1.980046, 6.736613], p80: [0.927933, 0.428277, 2.196806] },
  { id: "gpt_4o_inspect", name: "GPT-4o", released: "2024-05-13", frontier: true, originalSuite: false, p50: [6.991195, 4.001482, 12.905741], p80: [1.267009, 0.562997, 3.01517] },
  { id: "claude_3_5_sonnet_20240620_inspect", name: "Claude 3.5 Sonnet (June 2024)", released: "2024-06-20", frontier: true, originalSuite: false, p50: [11.395377, 5.489734, 22.384214], p80: [1.671757, 0.57927, 4.573519] },
  { id: "o1_preview", name: "o1-preview", released: "2024-09-12", frontier: true, originalSuite: false, p50: [20.326586, 11.716193, 33.379877], p80: [4.420545, 2.012646, 8.912444] },
  { id: "claude_3_5_sonnet_20241022_inspect", name: "Claude 3.5 Sonnet (October 2024)", released: "2024-10-22", frontier: true, originalSuite: false, p50: [20.522872, 10.144026, 40.82028], p80: [2.595677, 0.89379, 7.363864] },
  { id: "o1_inspect", name: "o1", released: "2024-12-05", frontier: true, originalSuite: false, p50: [38.831588, 21.164512, 64.95249], p80: [7.090121, 3.036033, 16.640636] },
  { id: "claude_3_7_sonnet_inspect", name: "Claude 3.7 Sonnet", released: "2025-02-24", frontier: true, originalSuite: false, p50: [60.388937, 33.006168, 104.226017], p80: [12.09179, 4.575608, 28.889879] },
  { id: "o3_inspect", name: "o3", released: "2025-04-16", frontier: true, originalSuite: false, p50: [119.732634, 74.615398, 190.943818], p80: [29.981603, 15.127348, 57.823511] },
  { id: "claude_4_opus_inspect", name: "Claude Opus 4", released: "2025-05-22", frontier: false, originalSuite: false, p50: [100.366123, 59.994073, 163.454074], p80: [20.429752, 8.483125, 41.937268] },
  { id: "claude_4_1_opus_inspect", name: "Claude Opus 4.1", released: "2025-08-05", frontier: false, originalSuite: false, p50: [100.472004, 59.272391, 159.451918], p80: [23.455761, 10.538456, 47.785951] },
  { id: "gpt_5_2025_08_07_inspect", name: "GPT-5", released: "2025-08-07", frontier: true, originalSuite: false, p50: [203.012577, 112.641357, 405.551565], p80: [38.312431, 19.184874, 70.093125] },
  { id: "gemini_3_pro", name: "Gemini 3 Pro", released: "2025-11-18", frontier: true, originalSuite: false, p50: [224.325884, 139.565157, 379.235434], p80: [54.142849, 25.650451, 103.295501] },
  { id: "gpt_5_1_codex_max_inspect", name: "GPT-5.1-Codex-Max", released: "2025-11-19", frontier: false, originalSuite: false, p50: [223.714694, 134.31077, 396.206723], p80: [50.632499, 27.30204, 88.365435] },
  { id: "claude_opus_4_5_inspect", name: "Claude Opus 4.5", released: "2025-11-24", frontier: true, originalSuite: false, p50: [292.994594, 161.717714, 623.704698], p80: [49.430584, 20.660485, 104.641318] },
  { id: "gpt_5_2", name: "GPT-5.2", released: "2025-12-11", frontier: true, originalSuite: false, p50: [352.249302, 198.067494, 815.177445], p80: [66.002649, 31.665111, 131.730719] },
  { id: "claude_opus_4_6_inspect", name: "Claude Opus 4.6", released: "2026-02-05", frontier: true, originalSuite: false, p50: [718.80683, 316.685725, 3633.786163], p80: [69.874587, 27.026521, 170.437873] },
  { id: "gpt_5_3_codex", name: "GPT-5.3-Codex", released: "2026-02-05", frontier: false, originalSuite: false, p50: [349.530732, 194.913134, 816.351994], p80: [54.739407, 22.361504, 122.058963] },
  { id: "gemini_3_1_pro", name: "Gemini 3.1 Pro", released: "2026-02-19", frontier: false, originalSuite: false, p50: [384.147435, 233.50073, 694.750898], p80: [89.801503, 52.025934, 158.618017] },
  { id: "gpt_5_4", name: "GPT-5.4", released: "2026-03-05", frontier: false, originalSuite: false, p50: [341.735276, 186.581591, 768.779526], p80: [53.877851, 23.957027, 108.679232] },
  { id: "claude_mythos_preview_early_inspect", name: "Claude Mythos Preview (early)", released: "2026-04-07", frontier: true, originalSuite: false, p50: [1044.780145, 508.876789, 3304.261235], p80: [185.911829, 97.30292, 398.514614] },
];
