// One parent bundle and six bundles derived from it, with the digests, sizes,
// and output errors computed by tools/figure-data/artifact-lineage.py (numpy
// 2.3.2, seed 20260924). The parent is a synthetic bundle, not a released
// model: config.json, tokenizer.json, and model.safetensors holding one
// 64 x 64 float32 weight matrix with heavy-tailed entries. Each child is
// written in the safetensors layout with its transformation recorded in the
// header metadata, and gets its own canonical manifest (schema, then one
// descriptor per file: path, role, media type, size, SHA-256).
//
// Output error is ||X W_child^T - X W_ref^T||_F / ||X W_ref^T||_F on 256
// held-out probe inputs; W_ref is the parent, except for the adapter merge,
// whose reference is the parent with the adapter applied unmerged. The figure
// evaluates the chapter's integrity gate accept(B) for the chosen child twice,
// against the parent's manifest and against the child's own, and compares the
// error with a threshold the reader sets (the chapter gives no number, so the
// threshold is illustrative).
//
// Two children differ only in the converter release written into the header:
// their tensors and error are identical and their digests are not. The
// stochastic-rounding child records its seed; the script also records the
// manifest of a seed 2 run.

import { defineFigure, type Lang, type State, type Text } from "./types.ts";
import { svg, el, text, g } from "./lib/svg.ts";
import { C, TYPE } from "./lib/theme.ts";
import { log } from "./lib/scale.ts";
import { textWidth } from "./lib/labels.ts";
import { wrapCJK } from "./lib/notation.ts";
import { int, sig, tpl } from "./lib/format.ts";

interface FileDesc { path: string; role: string; media: string; size: number; sha256: string }
interface Bundle { manifest: string; files: FileDesc[] }
interface Child extends Bundle { error: number; vsParent?: number; rerun?: { seed: number; manifest: string; error: number } }
type ChildKey = "bf16" | "int4-a" | "int4-b" | "int4-cal" | "int4-sr" | "lora-merge";
interface Lineage { parent: Bundle; children: Record<ChildKey, Child> }

// Generated by tools/figure-data/artifact-lineage.py; do not edit by hand.
const LINEAGE: Lineage = {
  parent: { manifest: "54c3c5f32009b6a0790414dcb024fabb7b87a9bb9f58c75fa56b285b150b4293", files: [{ path: "config.json", role: "config", media: "application/json", size: 56, sha256: "8c86fcfa6e8204524ae34d9721f0e606ea6044739b7e11d7ad626dddcfa3a258" }, { path: "model.safetensors", role: "weights", media: "safetensors", size: 16488, sha256: "36e6f52a50052baa38c77cec1ae3a8540b35e5eddbb36dde76570afc95f40712" }, { path: "tokenizer.json", role: "tokenizer", media: "application/json", size: 37, sha256: "66033d045e4bf1d31cc6b157cacd532c84ef8036fd01f6faf08637cf1b4afa1f" }] },
  children: {
    "bf16": { manifest: "d9707e66b21cb876e4683316dd36ee93336c8696dde18552e018bcfac2d156cc", error: 0.0015837, files: [{ path: "config.json", role: "config", media: "application/json", size: 57, sha256: "cf82f7e422ff0118abab1c36704c5b599c5a37814b58bb240cb2ecc77ad6cae7" }, { path: "model.safetensors", role: "weights", media: "safetensors", size: 8384, sha256: "b66fb8ef3983e49167b4e819a00a0578e4df1f860d5d9a4c2fe99f027c57fc3d" }, { path: "tokenizer.json", role: "tokenizer", media: "application/json", size: 37, sha256: "66033d045e4bf1d31cc6b157cacd532c84ef8036fd01f6faf08637cf1b4afa1f" }] },
    "int4-a": { manifest: "017e887bbb194712e43cdb3bda63589002c3b364cd0832b15d4440b5ebd735bf", error: 0.13022, files: [{ path: "config.json", role: "config", media: "application/json", size: 128, sha256: "9c34458f40eb8129ca9b49dbb5ddbed653908cde26aebb9b7933c1a7fc8b630e" }, { path: "model.safetensors", role: "weights", media: "safetensors", size: 2568, sha256: "4da6966d13c05265f993894bdbe16a4a05e7460b3eb35dc95a2e40e583a9878b" }, { path: "tokenizer.json", role: "tokenizer", media: "application/json", size: 37, sha256: "66033d045e4bf1d31cc6b157cacd532c84ef8036fd01f6faf08637cf1b4afa1f" }] },
    "int4-b": { manifest: "89aacf5840a33cc60febd4f9c875376bcdd732ccc349ac371097f9c92471b16f", error: 0.13022, files: [{ path: "config.json", role: "config", media: "application/json", size: 128, sha256: "9c34458f40eb8129ca9b49dbb5ddbed653908cde26aebb9b7933c1a7fc8b630e" }, { path: "model.safetensors", role: "weights", media: "safetensors", size: 2568, sha256: "f1b39eb979f3a232a2467f333efa67ca6f7f1b7fc530408d6cb0ecb86da759dd" }, { path: "tokenizer.json", role: "tokenizer", media: "application/json", size: 37, sha256: "66033d045e4bf1d31cc6b157cacd532c84ef8036fd01f6faf08637cf1b4afa1f" }] },
    "int4-cal": { manifest: "252c0dc4d2f5fee9b42b9de11fa433d17c3a95fde6a6960c842d5e8984818f95", error: 0.11916, files: [{ path: "config.json", role: "config", media: "application/json", size: 148, sha256: "03bd1705c66390fe115cb65221dd880157c1f4b8396334a0bba1754bdb15010c" }, { path: "model.safetensors", role: "weights", media: "safetensors", size: 2600, sha256: "22f583e9e22a2e70e9ae30c39c9c0ad1d1e18b7bbd02e5261da542cdfce3c093" }, { path: "tokenizer.json", role: "tokenizer", media: "application/json", size: 37, sha256: "66033d045e4bf1d31cc6b157cacd532c84ef8036fd01f6faf08637cf1b4afa1f" }] },
    "int4-sr": { manifest: "abc3ec51af62d561c5216455c207417ea5048e12b29cdd34494b4baedc84665d", error: 0.18455, rerun: { seed: 2, manifest: "726e6574f589bfed0a5f6a75d5a47d859857e77a8676f5cdf1d03e7bd355e824", error: 0.18785 }, files: [{ path: "config.json", role: "config", media: "application/json", size: 131, sha256: "24eb79b18ba4ab8af78cf04533b85d2f4ab9e33300016eda0f7965a797ec5f49" }, { path: "model.safetensors", role: "weights", media: "safetensors", size: 2584, sha256: "f9a6a23367fb616cee03dab9d09e5c96bd7bdc82615830a5ef2d2d1dc8584574" }, { path: "tokenizer.json", role: "tokenizer", media: "application/json", size: 37, sha256: "66033d045e4bf1d31cc6b157cacd532c84ef8036fd01f6faf08637cf1b4afa1f" }] },
    "lora-merge": { manifest: "11fee40592f98ec9ba67a1ebc7d4616ad82726a74c95fd5693e5aeb7cb5a5017", error: 0.0016297, vsParent: 0.23526, files: [{ path: "config.json", role: "config", media: "application/json", size: 57, sha256: "cf82f7e422ff0118abab1c36704c5b599c5a37814b58bb240cb2ecc77ad6cae7" }, { path: "model.safetensors", role: "weights", media: "safetensors", size: 8416, sha256: "fd0839dc5555569f8116b6bfa7917e736d550111768a28d7c4faaf749411b6c3" }, { path: "tokenizer.json", role: "tokenizer", media: "application/json", size: 37, sha256: "66033d045e4bf1d31cc6b157cacd532c84ef8036fd01f6faf08637cf1b4afa1f" }] },
  },
};

const KEYS: ChildKey[] = ["bf16", "int4-a", "int4-b", "int4-cal", "int4-sr", "lora-merge"];

// Name and transformation of each child, as its lineage record states them.
const META: Record<ChildKey, { name: Text; tool: Text; detail: Text }> = {
  "bf16": { name: { en: "bfloat16 cast", zh: "转为 bfloat16" }, tool: { en: "cast 1.0.0, round to nearest even", zh: "cast 1.0.0，就近舍入到偶数" },
    detail: { en: "cast 1.0.0: float32 to bfloat16, round to nearest even; config dtype set to bfloat16", zh: "cast 1.0.0：float32 转为 bfloat16，就近舍入到偶数；配置中的 dtype 改为 bfloat16" } },
  "int4-a": { name: { en: "int4, round to nearest", zh: "int4，就近舍入" }, tool: { en: "converter 1.4.0, groups of 32", zh: "converter 1.4.0，每组 32 个" },
    detail: { en: "converter 1.4.0: symmetric int4 per group of 32 inputs, round to nearest, one float16 scale per group", zh: "converter 1.4.0：对称 int4，每 32 个输入一组，就近舍入，每组一个 float16 缩放因子" } },
  "int4-b": { name: { en: "int4, round to nearest", zh: "int4，就近舍入" }, tool: { en: "converter 1.5.0, groups of 32", zh: "converter 1.5.0，每组 32 个" },
    detail: { en: "converter 1.5.0: symmetric int4 per group of 32 inputs, round to nearest, one float16 scale per group", zh: "converter 1.5.0：对称 int4，每 32 个输入一组，就近舍入，每组一个 float16 缩放因子" } },
  "int4-cal": { name: { en: "int4, calibrated clip", zh: "int4，校准截断" }, tool: { en: "converter 1.4.0, 128 calibration inputs", zh: "converter 1.4.0，128 个校准输入" },
    detail: { en: "converter 1.4.0: int4 per group of 32, each group's clip ratio chosen from 1.00 to 0.65 to minimize activation-weighted error on 128 calibration inputs", zh: "converter 1.4.0：int4，每 32 个输入一组；每组的截断比例在 1.00 至 0.65 之间选取，使 128 个校准输入上按激活加权的误差最小" } },
  "int4-sr": { name: { en: "int4, stochastic rounding", zh: "int4，随机舍入" }, tool: { en: "converter 1.4.0, rounding seed 1", zh: "converter 1.4.0，舍入种子 1" },
    detail: { en: "converter 1.4.0: int4 per group of 32, stochastic rounding with seed 1 written into the header", zh: "converter 1.4.0：int4，每 32 个输入一组，随机舍入，种子 1 写入头部" } },
  "lora-merge": { name: { en: "LoRA merge, bfloat16", zh: "合并 LoRA，bfloat16" }, tool: { en: "merge 1.0.0, rank 8, alpha 16", zh: "merge 1.0.0，秩 8，alpha 16" },
    detail: { en: "merge 1.0.0: W + (alpha / r) B A with a rank 8 adapter and alpha 16, merged in float32, stored as bfloat16", zh: "merge 1.0.0：W + (alpha / r) B A，适配器秩为 8，alpha 为 16，以 float32 合并后存为 bfloat16" } },
};

const labels = {
  en: {
    title: "One parent bundle, six derived bundles",
    parent: "Parent bundle",
    parentNote: "float32, synthetic",
    manifest: "manifest {h}",
    axis: "output error vs reference",
    tau: "τ = {v}",
    accept: "accept", reject: "reject", accepted: "accepted", rejected: "rejected",
    row: "{m} · {s} · error {e}",
    record: "Lineage record: {name}",
    rSource: "Source",
    rSourceV: "parent manifest {h}",
    rTool: "Transformation",
    rOutput: "Output",
    rOutputV: "manifest {h}; {changed}",
    changedFile: "{p} {a} → {b}",
    sameFile: "{p} unchanged",
    rEval: "Evaluation",
    rEvalV: "error {e} against {ref} on 256 probe inputs; τ = {t}: {v}",
    refParent: "the parent",
    refMerge: "the parent with the adapter applied unmerged",
    rGate: "Gate accept(B)",
    rGateV: "with the parent's manifest: rejected, digest mismatch on {files}; with its own manifest: verified, 3 files",
    rNote: "Note",
    noteTwin: "Same tensors and error as {twin}; only the converter release in the header differs, so the digest differs.",
    noteSeed: "Nondeterministic: the seed is recorded. A seed 2 run gives manifest {h} and error {e}.",
    noteMerge: "Against the parent alone the error is {e}: the change the adapter is meant to make.",
    noteCal: "The calibration inputs are recorded with the lineage; other inputs choose other clips and bytes.",
    noteCast: "The smallest change here, and still a new digest for the weights and the config.",
    describe: "{name} ({tool}): manifest {h}, output error {e} against {ref}, so with τ = {t} it is {v}. The parent's manifest rejects it on {files}; its own manifest verifies all 3 files.",
  },
  zh: {
    title: "一个父制品包与六个派生制品包",
    parent: "父制品包",
    parentNote: "float32，合成数据",
    manifest: "清单 {h}",
    axis: "相对参照的输出误差",
    tau: "τ = {v}",
    accept: "通过", reject: "拒绝", accepted: "通过", rejected: "拒绝",
    row: "{m} · {s} · 误差 {e}",
    record: "血统记录：{name}",
    rSource: "来源",
    rSourceV: "父清单 {h}",
    rTool: "转换",
    rOutput: "输出",
    rOutputV: "清单 {h}；{changed}",
    changedFile: "{p} {a} → {b}",
    sameFile: "{p} 未变",
    rEval: "评测",
    rEvalV: "在 256 个探测输入上相对{ref}的误差为 {e}；τ = {t}：{v}",
    refParent: "父制品",
    refMerge: "未合并、运行时加载适配器的父制品",
    rGate: "闸门 accept(B)",
    rGateV: "用父清单验证：拒绝，{files} 摘要不符；用自身清单验证：通过，共 3 个文件",
    rNote: "说明",
    noteTwin: "张量和误差与 {twin}完全相同，只有头部记录的 converter 版本不同，因此摘要不同。",
    noteSeed: "转换不确定，已记录种子。用种子 2 重跑，得到清单 {h}，误差 {e}。",
    noteMerge: "若只与父制品比较，误差为 {e}，这正是适配器要带来的改变。",
    noteCal: "校准输入随血统一并记录；换一批输入会选出不同的截断比例，写出不同的字节。",
    noteCast: "这是改动最小的一项，权重和配置的摘要仍然都变了。",
    describe: "{name}（{tool}）：清单 {h}，相对{ref}的输出误差为 {e}，τ = {t} 时判定为{v}。父清单验证时 {files} 不符而被拒绝；自身清单验证 3 个文件全部通过。",
  },
};
type L = typeof labels.en;
type P = { child: ChildKey; tau: number };

const short = (h: string) => h.slice(0, 8);
const fmtE = (e: number) => e.toPrecision(3);
const fmtT = (v: number) => sig(v, 3);
const bytes = (n: number, lang: Lang) => (lang === "zh" ? `${int(n)} 字节` : `${int(n)} B`);

function changedFiles(c: Child): string[] {
  return c.files.filter((f, i) => f.sha256 !== LINEAGE.parent.files[i].sha256).map((f) => f.path);
}

function verdict(c: Child, tau: number): boolean {
  return c.error <= tau;
}

function describe(st: State<P>, lang: Lang): string {
  const L = labels[lang];
  const c = LINEAGE.children[st.p.child];
  return tpl(L.describe, {
    name: META[st.p.child].name[lang], tool: META[st.p.child].tool[lang], h: short(c.manifest), e: fmtE(c.error),
    ref: st.p.child === "lora-merge" ? L.refMerge : L.refParent, t: fmtT(st.p.tau),
    v: verdict(c, st.p.tau) ? L.accepted : L.rejected, files: changedFiles(c).join(lang === "zh" ? "、" : " and "),
  });
}

// ---------------------------------------------------------------- render

const LH = 15;

// wrapCJK, rewrapped one glyph narrower when its line-start rule pushes a
// line past the width, and with an opening bracket never ending a line.
function lines(s: string, size: number, width: number): string[] {
  let out = wrapCJK(s, size, width);
  if (out.some((ln) => textWidth(ln, size) > width)) out = wrapCJK(s, size, width - size * 1.02);
  for (let i = 0; i < out.length - 1; i++) {
    while (/[（「]$/u.test(out[i])) {
      out[i + 1] = out[i].slice(-1) + out[i + 1];
      out[i] = out[i].slice(0, -1);
    }
  }
  return out;
}

function block(x: number, y: number, ls: string[], a: Record<string, string | number>): string {
  return ls.map((ln, i) => text(x, y + i * LH, ln, a)).join("");
}

function outputText(c: Child, L: L, lang: Lang): string {
  const sep = lang === "zh" ? "；" : "; ";
  const parts = c.files.map((f, i) => {
    const p = LINEAGE.parent.files[i];
    if (f.sha256 === p.sha256) return tpl(L.sameFile, { p: f.path });
    const s = tpl(L.changedFile, { p: f.path, a: short(p.sha256), b: short(f.sha256) });
    return f.size !== p.size ? `${s}${lang === "zh" ? "，" : ", "}${bytes(p.size, lang)} → ${bytes(f.size, lang)}` : s;
  });
  return tpl(L.rOutputV, { h: short(c.manifest), changed: parts.join(sep) });
}

function noteText(k: ChildKey, L: L, lang: Lang): string {
  const c = LINEAGE.children[k];
  const twin = (o: ChildKey) => `${META[o].name[lang]}${lang === "zh" ? "（" : " ("}${META[o].tool[lang].split(/[,，]/)[0]}${lang === "zh" ? "）" : ")"}`;
  switch (k) {
    case "bf16": return L.noteCast;
    case "int4-a": return tpl(L.noteTwin, { twin: twin("int4-b") });
    case "int4-b": return tpl(L.noteTwin, { twin: twin("int4-a") });
    case "int4-cal": return L.noteCal;
    case "int4-sr": return tpl(L.noteSeed, { h: short(c.rerun!.manifest), e: fmtE(c.rerun!.error) });
    case "lora-merge": return tpl(L.noteMerge, { e: fmtE(c.vsParent!) });
  }
}

function verdictMark(x: number, y: number, ok: boolean, L: L): string {
  return el("circle", { cx: x + 5, cy: y - 4, r: 4.5, fill: ok ? C.good : C.bad })
    + text(x + 14, y, ok ? L.accept : L.reject, { "font-size": TYPE.small, class: ok ? "fig-t-strong" : "fig-t-muted" });
}

function render(st: State<P>, lang: Lang): string {
  const L = labels[lang];
  const p = st.p;
  const w = st.w;
  const narrow = w < 480;
  const parts: string[] = [];
  parts.push(text(0, 14, L.title, { "font-size": TYPE.label, class: "fig-t-strong" }));

  const par = LINEAGE.parent;
  const role = (r: string) => par.files.find((f) => f.role === r)!;
  const verdictW = Math.max(textWidth(L.accept, TYPE.small), textWidth(L.reject, TYPE.small)) + 20;

  // Geometry of the tree.
  let y = 30;
  let pw: number, ph: number, px: number, py: number; // parent box
  let cx0: number, plot0: number, plot1: number;
  const rowH = narrow ? 76 : 50;
  if (narrow) {
    pw = w; ph = 4 * LH + 14; px = 0; py = y;
    cx0 = 20; plot0 = 26; plot1 = w - 8;
  } else {
    const texts = [`${bytes(par.files[1].size, lang)}, ${L.parentNote}`, `tokenizer ${short(par.files[2].sha256)}`, tpl(L.manifest, { h: short(par.manifest) })];
    pw = Math.max(152, ...texts.map((t) => textWidth(t, TYPE.small) + 22)); ph = 6 * LH + 14; px = 0;
    cx0 = pw + 30; plot1 = w - verdictW - 8; plot0 = plot1 - Math.min(150, Math.max(110, w * 0.2));
    py = 0; // set below, centered on the rows
  }
  const x = log([0.001, 0.5], [plot0, plot1]);
  const ticks = [0.001, 0.01, 0.1];

  // Axis header over the error column (desktop) or over the list (phone).
  const axisTop = narrow ? y + ph + 18 : y;
  parts.push(text(narrow ? plot0 : plot0, axisTop + 11, L.axis, { "font-size": TYPE.small, class: "fig-t-muted" }));
  for (const t of ticks) parts.push(text(x(t), axisTop + 26, sig(t, 1), { "font-size": TYPE.small, "text-anchor": "middle", class: "fig-t-num fig-t-muted" }));
  const rowsTop = axisTop + 34;
  const rowsBottom = rowsTop + KEYS.length * rowH;
  if (!narrow) py = Math.max(y, (rowsTop + rowsBottom) / 2 - ph / 2);

  // Decade gridlines and the threshold under the rows' error strips.
  const gridTop = rowsTop, gridBottom = rowsBottom - 6;
  if (!narrow) {
    for (const t of ticks) parts.push(el("line", { x1: x(t), x2: x(t), y1: gridTop, y2: gridBottom, stroke: C.grid, "stroke-width": 1 }));
  }

  // Parent box.
  parts.push(el("rect", { x: px, y: py, width: pw, height: ph, rx: 6, fill: C.panel, stroke: C.rule, "stroke-width": 1 }));
  const pl: Array<[string, string]> = narrow
    ? [[`${L.parent} · ${L.parentNote}`, "fig-t-strong"],
      [`${tpl(L.manifest, { h: short(par.manifest) })} · ${bytes(role("weights").size, lang)}`, "fig-t-num"],
      [`config ${short(role("config").sha256)} · weights ${short(role("weights").sha256)}`, "fig-t-num fig-t-muted"],
      [`tokenizer ${short(role("tokenizer").sha256)}`, "fig-t-num fig-t-muted"]]
    : [[L.parent, "fig-t-strong"], [tpl(L.manifest, { h: short(par.manifest) }), "fig-t-num"],
      [`config ${short(role("config").sha256)}`, "fig-t-num fig-t-muted"], [`weights ${short(role("weights").sha256)}`, "fig-t-num fig-t-muted"],
      [`tokenizer ${short(role("tokenizer").sha256)}`, "fig-t-num fig-t-muted"], [`${bytes(role("weights").size, lang)}, ${L.parentNote}`, "fig-t-muted"]];
  pl.forEach(([s, cls], i) => parts.push(text(px + 10, py + 19 + i * LH, s, { "font-size": i === 0 ? TYPE.body : TYPE.small, class: cls })));

  // Connectors: one trunk, one elbow per child.
  const trunkX = narrow ? 8 : pw + 14;
  const elbowY = (i: number) => rowsTop + i * rowH + 12;
  if (narrow) {
    parts.push(el("line", { x1: trunkX, x2: trunkX, y1: py + ph, y2: elbowY(KEYS.length - 1), stroke: C.rule, "stroke-width": 1.2 }));
  } else {
    const midY = py + ph / 2;
    parts.push(el("line", { x1: pw, x2: trunkX, y1: midY, y2: midY, stroke: C.rule, "stroke-width": 1.2 }));
    parts.push(el("line", { x1: trunkX, x2: trunkX, y1: Math.min(midY, elbowY(0)), y2: Math.max(midY, elbowY(KEYS.length - 1)), stroke: C.rule, "stroke-width": 1.2 }));
  }

  KEYS.forEach((k, i) => {
    const c = LINEAGE.children[k];
    const ry = rowsTop + i * rowH;
    const sel = k === p.child;
    const ok = verdict(c, p.tau);
    if (sel) parts.push(el("rect", { x: cx0 - 6, y: ry, width: w - cx0 + 6, height: rowH - 4, rx: 4, fill: C.panel }));
    parts.push(el("line", { x1: trunkX, x2: cx0 - 6, y1: elbowY(i), y2: elbowY(i), stroke: C.rule, "stroke-width": 1.2 }));
    parts.push(text(cx0, ry + 16, META[k].name[lang], { "font-size": TYPE.body, class: sel ? "fig-t-strong" : undefined }));
    const textW = (narrow ? w - verdictW : plot0 - 12) - cx0;
    parts.push(text(cx0, ry + 31, lines(META[k].tool[lang], TYPE.small, textW)[0], { "font-size": TYPE.small, class: "fig-t-muted" }));
    parts.push(text(cx0, ry + 45, tpl(L.row, { m: tpl(L.manifest, { h: short(c.manifest) }), s: bytes(c.files[1].size, lang), e: fmtE(c.error) }), { "font-size": TYPE.small, class: "fig-t-num fig-t-muted" }));
    // Error strip and dot.
    const sy = narrow ? ry + 62 : ry + rowH / 2 - 2;
    parts.push(el("line", { x1: plot0, x2: plot1, y1: sy, y2: sy, stroke: C.rule, "stroke-width": 1 }));
    if (narrow) {
      for (const t of ticks) parts.push(el("line", { x1: x(t), x2: x(t), y1: sy - 3, y2: sy + 3, stroke: C.rule, "stroke-width": 1 }));
      parts.push(el("line", { x1: x(p.tau), x2: x(p.tau), y1: sy - 8, y2: sy + 8, stroke: C.ink2, "stroke-width": 1.2, "stroke-dasharray": "3 2" }));
    }
    parts.push(el("circle", { cx: x(c.error), cy: sy, r: 5, fill: C.c1, stroke: C.paper, "stroke-width": 1.5 }));
    parts.push(verdictMark(w - verdictW + 4, narrow ? ry + 16 : ry + rowH / 2 + 2, ok, L));
    parts.push(el("rect", { x: cx0 - 6, y: ry, width: w - cx0 + 6, height: rowH - 4, fill: "transparent", "data-fig-set": `child=${k}`, class: "fig-hit" }));
  });
  if (!narrow) {
    const tx = x(p.tau);
    parts.push(el("line", { x1: tx, x2: tx, y1: gridTop - 2, y2: gridBottom, stroke: C.ink2, "stroke-width": 1.2, "stroke-dasharray": "3 2" }));
    const lab = tpl(L.tau, { v: fmtT(p.tau) });
    const lw = textWidth(lab, TYPE.small);
    parts.push(text(Math.min(Math.max(tx, plot0 + lw / 2), w - lw / 2), rowsBottom + 8, lab, { "font-size": TYPE.small, "text-anchor": "middle", class: "fig-t-strong fig-t-num" }));
  } else {
    parts.push(text(plot0, rowsBottom + 6, tpl(L.tau, { v: fmtT(p.tau) }) + (lang === "zh" ? "（虚线）" : " (dashed)"), { "font-size": TYPE.small, class: "fig-t-strong fig-t-num" }));
  }

  // The chosen child's lineage record.
  y = rowsBottom + 34;
  const c = LINEAGE.children[p.child];
  const head = lines(tpl(L.record, { name: `${META[p.child].name[lang]}${lang === "zh" ? "，" : ", "}${META[p.child].tool[lang].split(/[,，]/)[0]}` }), TYPE.label, w);
  parts.push(block(0, y, head, { "font-size": TYPE.label, class: "fig-t-strong" }));
  y += (head.length - 1) * LH + 10;
  const items: Array<[string, string]> = [
    [L.rSource, tpl(L.rSourceV, { h: short(LINEAGE.parent.manifest) })],
    [L.rTool, META[p.child].detail[lang]],
    [L.rOutput, outputText(c, L, lang)],
    [L.rEval, tpl(L.rEvalV, { e: fmtE(c.error), ref: p.child === "lora-merge" ? L.refMerge : L.refParent, t: fmtT(p.tau), v: verdict(c, p.tau) ? L.accept : L.reject })],
    [L.rGate, tpl(L.rGateV, { files: changedFiles(c).join(lang === "zh" ? "、" : " and ") })],
    [L.rNote, noteText(p.child, L, lang)],
  ];
  const labW = narrow ? 0 : Math.max(...items.map(([k]) => textWidth(k, TYPE.small))) + 16;
  for (const [k, v] of items) {
    parts.push(el("line", { x1: 0, x2: w, y1: y, y2: y, stroke: C.grid, "stroke-width": 1 }));
    const vl = lines(v, TYPE.body, w - labW - 10);
    if (narrow) {
      parts.push(text(0, y + 15, k, { "font-size": TYPE.small, class: "fig-t-muted" }));
      parts.push(block(0, y + 31, vl, { "font-size": TYPE.body }));
      y += 22 + vl.length * LH;
    } else {
      parts.push(text(0, y + 16, k, { "font-size": TYPE.small, class: "fig-t-muted" }));
      parts.push(block(labW, y + 16, vl, { "font-size": TYPE.body }));
      y += 8 + vl.length * LH;
    }
  }
  return svg(w, y + 4, describe(st, lang), g({ class: "fig-lineage" }, ...parts));
}

export default defineFigure({
  name: "artifact-lineage",
  title: { en: labels.en.title, zh: labels.zh.title },
  labels,
  params: {
    child: {
      kind: "choice", control: "select", label: { en: "Derived bundle", zh: "派生制品包" }, default: "int4-b",
      options: KEYS.map((k) => ({ value: k, label: { en: `${META[k].name.en} (${META[k].tool.en.split(",")[0]})`, zh: `${META[k].name.zh}（${META[k].tool.zh.split("，")[0]}）` } })),
    },
    tau: {
      kind: "range", scale: "log", label: { en: "Acceptance threshold τ on output error", zh: "输出误差的验收阈值 τ" },
      min: 0.001, max: 0.5, default: 0.15,
    },
  },
  render,
  describe,
});
