// Block-scaled quantization of one real vector: every group of g consecutive
// values shares one scale s_g, each value is stored as an element code q_i,
// and the reader sees what survives, x̂_i = s_g · q_i (quantization-kernels
// chapter, symmetric case z_g = 0):
//
//   q_i = q(x_i / s_g), saturated at ±q_max,     x̂_i = s_g q_i,
//   b_eff = b + b_s / g   bits per value (the chapter's effective payload).
//
// q rounds to the nearest element value, ties to even. Elements:
// - INT4: the integers −7 … 7 (q_max = 7), as in the chapter's runnable.
// - FP4 E2M1: 0, ±0.5, ±1, ±1.5, ±2, ±3, ±4, ±6 (q_max = 6), the MXFP4 and
//   NVFP4 element (OCP Microscaling Formats v1.0).
// - FP8 E4M3: 1 sign, 4 exponent, 3 mantissa bits, bias 7, subnormals, no
//   Inf, largest finite 448 (Micikevicius et al. 2022).
// Scales, from the block maximum amax = max |x_i|:
// - FP32 or FP16: s_g = amax / q_max, rounded to the scale's format.
// - E8M0 (MX rule, Rouhani et al. 2023, Algorithm 1): s_g =
//   2^(⌊log2 amax⌋ − e_max), e_max the exponent of the element's largest
//   value (2 for E2M1 and INT4, 8 for E4M3); values that land above q_max
//   are clamped.
// - E4M3 with an FP32 tensor scale (NVFP4 rule, NVIDIA 2025, "Pretraining
//   Large Language Models with NVFP4", appendix B): s_T = amax_T / (q_max ·
//   448) over the whole vector, and s_g = e4m3(amax / q_max / s_T) · s_T.
//
// The two vectors are real: layer 12 of Qwen/Qwen2.5-0.5B (revision 060db64),
// row 0 of the query-projection weight and the 896 values that projection
// receives for the token " mat" in "The cat sat on the mat because it was
// tired." (tools/figure-data/block-scaling-vectors.py regenerates VECTORS).
// The FP32 tensor scale is taken over the shown vector, which stands in for
// the tensor.

import { defineFigure, type Lang, type State } from "./types.ts";
import { svg, el, text, g, esc } from "./lib/svg.ts";
import { C, TYPE } from "./lib/theme.ts";
import { linear } from "./lib/scale.ts";
import { axis, axisHeight } from "./lib/axis.ts";
import { textWidth } from "./lib/labels.ts";
import { wrapCjk as wrap } from "./lib/kinsoku.ts";
import { sig, fixed, tpl } from "./lib/format.ts";

// ---------------------------------------------------------------- data

// Regenerated by tools/figure-data/block-scaling-vectors.py; four significant
// digits, the values the figure quantizes.
const VECTORS = {
  weight: [-0.01025, -0.0009232, 0.04468, 0.008301, 0.004028, -0.08301, 0.001686, 0.006653, -0.0002804, -0.02502, 0.001106, -0.004456, 0.01685, -0.02881, -0.05273, 0.001068, -0.008789, 0.03516, -0.008545, -0.01599, 0.02087, 0.004456, -0.01483, -0.02783, -0.01276, -0.03564, -0.00647, -0.01215, -0.01123, -0.02087, 0.01508, 0.02673, -0.03638, 0.0199, -0.02014, 0.03345, 0.01611, 0.00946, 0.01685, 0.01587, -0.0144, -0.001587, 0.02332, 0.006317, 0.03149, 0.02625, -0.01501, -0.01831, -0.02576, 0.01385, 0.002563, 0.01379, 0.005066, 0.01648, 0.06104, 0.003036, -0.00708, -0.007812, -0.0116, 0.01056, -0.01343, -0.00322, 0.002335, 0.00354, 0.03027, 0.03369, -0.02881, 0.04468, 0.0152, -0.006927, 0.03296, 0.04883, 0.001389, 0.04468, 0.02258, -0.04321, 0.003754, 0.03149, -0.04126, 0.03857, -0.02124, -0.01367, 5.15e-05, 0.0116, -0.0282, 0.00206, 0.01379, 0.02478, 0.009521, -0.02185, 0.02258, 0.003479, -0.008301, 0.01001, -0.002426, -0.002991, 0.006958, 0.02539, 0.01416, 0.009583, -0.07471, 0.01782, 0.007629, -0.01636, -0.02502, -0.04932, -0.03784, 0.0188, 0.01904, 0.01068, -0.004608, -0.01208, -0.01672, 0.007294, 0.0249, 0.03418, 0.00885, -0.01404, -0.02087, -0.021, -0.01013, 0.01685, -0.01575, -0.007568, 0.03882, -0.02173, -0.02551, -0.03516, 0.01404, 0.0188, -0.01794, 0.03638, -0.04834, 0.001938, 0.0293, 0.04248, -0.002716, -0.002563, 0.002121, -7.963e-05, 0.03467, 7.439e-05, 0.009094, 0.02258, 0.006958, 0.02478, 0.01453, -0.006775, -0.02246, -0.0481, -0.01379, -0.02051, -0.01758, 0.008911, -0.008667, -0.02344, 0.007935, 0.01007, 0.01831, 0.03882, 0.01099, -0.02795, 0.01685, -0.01343, 0.01685, -0.02014, 0.03442, 0.02222, -0.03174, 0.006439, -0.01672, 0.01782, 0.00647, -0.05591, -0.009521, 0.01404, 0.01001, -0.06543, -0.02197, -0.00383, -0.0144, -0.03467, 0.001518, 0.01807, 0.01587, -0.02112, 0.006805, 0.009644, -0.03784, 0.004364, 0.01068, -0.03467, -0.0177, -0.009827, -0.02319, -0.01111, 0.01135, 0.01477, 0.02051, -0.006989, 0.026, -0.001511, 0.01074, -0.05103, 0.009338, -0.02344, -0.007294, -0.03015, 0.02332, -0.01794, 0.01917, 0.02051, 0.01721, -0.03711, -0.03564, -0.001091, 0.004395, 0.003738, 0.008911, -0.04956, 0.002518, -0.0437, 0.004913, 0.03003, -0.008789, -0.005188, 0.006439, 0.07227, -0.004608, -0.003082, -0.001137, 0.01398, -0.009766, -0.002838, 0.02686, -0.01233, 0.02991, 0.01892, 0.01917, 0.02087, 0.01477, 0.02197, 0.04688, 0.003143, 0.009094, 0.004913, -0.04712, 0.02686, -0.008667, -0.006104, -0.0177, -0.01062, -0.03613, 0.00531, -0.001907, -0.01196, 0.01575, 0.01831, -0.02258, -0.0238, 0.02258, 0.02478, 0.01624, 0.01117, -0.01941, 0.01172, -0.004944, -0.02124, -0.01495, 0.01953, 0.04883, -0.0415, -0.00824, 0.00415, 0.0199, -0.05811, -0.01379, -0.002335, 0.02734, -0.0199, 0.01123, -0.03662, -0.01709, 0.01508, -0.05469, 0.01471, -0.0004749, -0.0004883, 0.01526, -0.02295, -0.06079, -0.0127, -0.009277, 0.01648, 0.04858, -0.03564, 0.0002069, 0.05493, -0.02087, -0.02197, -0.007996, 0.02075, -0.003189, -0.01624, -0.01324, 0.03662, -0.006805, -0.01953, 0.03564, 0.03735, -0.004425, -0.01318, -0.04028, -0.04395, -0.01501, 0.02551, -0.01733, -0.05762, 0.008789, -0.008606, 0.01709, 0.004395, 0.009827, 0.0481, 0.005707, 0.03369, 0.007782, 0.0004616, -0.008118, -0.0188, 0.009338, 0.008423, 0.005859, -0.01007, 0.01105, -0.02527, 0.02893, -0.0002689, 0.01636, -0.04224, 0.04907, -0.005981, 0.01459, -0.03113, -0.02979, 0.01215, -0.0001063, -0.04541, 0.001205, 0.03125, -0.05762, -0.00264, 0.026, 0.04663, -0.01385, -0.01184, -0.007629, -0.00766, -0.03467, 0.04297, -0.003708, -0.02332, 0.01196, -0.0332, -0.01172, 0.01489, -0.06152, -0.005585, 0.01202, -0.01648, -0.009033, 0.02637, 0.01245, 0.02893, 0.01672, 0.02417, 0.02161, -0.0008926, 0.01575, 0.02246, -0.01044, -0.01965, 0.01282, -0.03809, 0.03906, 0.01379, 0.02441, -0.00531, 0.003494, -0.007233, -0.01831, -0.03149, -0.005615, -0.01349, 0.03882, -0.03979, 0.0354, -0.003052, 0.01782, 0.02002, 0.03394, -0.0271, 0.003387, 0.0304, -0.02808, -0.01196, 0.0249, 0.02844, 0.0116, -0.05078, -0.004486, 0.04053, 0.01434, -0.02686, 0.007935, 0.02722, -0.001427, -0.04297, 0.01672, -0.06738, -0.05005, -0.0376, 0.002243, -0.01074, -0.05054, -0.03613, 0.01172, -0.0708, -0.02563, -0.03711, 0.001762, -0.03711, -0.01489, -0.02881, 0.001076, -0.06641, -0.0002375, 0.02979, -0.06689, -0.0293, 0.01978, 0.04199, 0.008057, 0.021, 0.006042, -0.06226, -0.009216, 0.07861, -0.01337, -0.009399, -0.002548, -0.01471, -0.03394, 0.00264, 0.0166, 0.02698, 0.01892, 0.03979, 0.04004, 0.03003, 0.03564, -0.01538, -0.03491, -0.04102, 0.02393, 0.009644, -0.002197, -0.008972, -0.02368, -0.009888, 0.00531, 0.005737, 0.0415, 0.004028, -0.01196, 0.05444, 0.009521, 0.009277, 0.01453, 0.03174, 0.002716, -0.00235, -0.004211, 0.01111, -0.003708, -0.01648, 0.04053, 0.006409, -0.002716, 0.02307, 0.007202, -0.0116, -0.03735, 0.008667, -0.01575, -0.0332, -0.02747, 0.03271, 0.013, 0.0376, -0.00119, 0.02075, -0.01288, 0.01062, -0.01471, -0.03003, 0.02991, -0.01398, -0.021, 0.02466, 0.02209, -0.002121, 0.02258, 0.008118, -0.03809, -0.001434, -0.009277, -0.03711, 0.001297, 0.01434, 0.01355, -0.001251, 0.01611, 0.006653, -0.007629, 0.02161, 0.00769, 0.005249, 0.04297, 0.0459, 0.01208, 0.005676, -0.005219, 0.02832, -0.01239, -0.003937, -0.006897, -0.03418, -0.004944, 0.0144, 0.01636, -0.004333, 0.01227, 0.02856, 0.005646, 0.005371, 0.01831, -0.02234, -0.02783, -0.02222, 0.02649, 0.004211, 0.01965, 0.01227, 0.04004, 0.02063, -0.03467, 0.0791, 0.02698, -0.01166, -0.02039, -0.004791, -0.02307, -0.009827, 0.002319, 0.01001, 0.05957, -0.002625, 0.02661, -0.004608, -0.01184, 0.01074, 0.005615, 0.05054, 0.002853, -0.04248, -0.01392, -0.0001187, 0.01221, 0.04492, 0.02185, 0.01367, -0.002914, 0.02625, -0.03979, 0.001755, 0.06445, -0.01807, 0.06592, -0.02649, -0.01105, -0.01929, -0.03345, 0.02734, -0.004883, 0.03857, 0.04712, -0.008484, 0.02271, -0.01831, -0.002106, 0.02698, 0.02185, -0.01245, 0.02368, 0.03516, 0.06445, 0.001945, -0.0009613, 0.02478, 0.02502, 0.0238, 0.01624, -0.04126, 0.02148, -0.04077, -0.02393, 0.03589, -0.01843, -0.01562, 0.04053, -0.02124, 0.04102, 0.013, -0.04468, 0.006165, -0.01648, -0.008789, 0.004486, -0.01306, 0.01312, 0.007721, -0.02563, -0.0271, -0.02002, 0.04053, 0.008484, -0.00824, 0.04541, 0.04712, -0.01599, -0.005646, 0.007416, 0.01562, 0.04492, 0.02185, -0.001572, -0.01208, 0.002045, 0.01239, -0.01306, -0.03809, 0.03833, 0.006104, 0.008728, 0.0105, -0.001122, -0.003357, 0.02942, 0.01392, -0.02551, -0.0009422, 0.01672, 0.01843, 0.02515, 0.01904, 0.007538, -0.00708, 0.009644, -0.01465, 0.04785, 0.006561, 0.002548, -0.01929, 0.006073, -0.0271, -0.004211, -0.06494, 0.003571, -0.03833, -0.03149, -0.01202, 0.004272, -0.01282, 0.005249, -0.0188, 0.0376, -0.02161, -0.01721, -0.00293, 0.01599, 0.01782, 0.0105, -0.01215, 0.008545, -0.01843, -0.01453, -0.006805, 0.01562, 0.03394, -0.02588, 0.003967, -0.02673, -0.06055, -0.03418, 0.007019, 0.005493, -0.01215, -0.03711, -0.02393, 0.05322, -0.01208, 0.03076, 0.03564, 0.02124, -0.004333, -0.06006, -0.02222, -0.05005, 0.001343, 0.02673, -0.02087, 0.02466, 0.05273, -0.03064, -0.03882, -0.02051, 0.002151, 0.005188, 0.08203, 0.04077, -0.0238, 0.03564, -0.04175, -0.005615, 0.02368, 0.0002232, 0.01392, -0.03467, 0.01135, 0.006165, 0.07617, 0.02344, -0.08105, -0.02454, 0.01074, -0.0166, 0.0332, -0.02783, 0.04614, -0.006897, -0.0332, -0.04541, 0.01978, -0.001984, 0.013, -0.01471, -0.03442, 0.03955, -0.02454, 0.01471, 0.0007935, -0.002502, 0.02563, 0.01025, 0.02319, -0.01477, -0.01636, 0.01978, 0.008423, 0.021, -0.001984, 0.000721, 0.02429, 0.01117, -0.0354, -0.02795, 0.05908, 0.008301, -0.01758, 0.06982, -0.03076, 0.03064, -0.0004654, 0.02734, 0.04565, -0.02014, -0.00824, 0.01721, -0.004791, 0.02161, 0.001709, 0.0249, 0.009277, -0.01587, -0.02283, -0.02991, -0.008972, -0.03369, 0.01123, -0.006592, 0.0415, -0.01611, 0.01123, 0.0144, 0.0141, -0.007446, 0.02856, 0.0354, 0.02295, -0.02185, -0.02734, 0.004089, -0.01337, -0.02222, 0.03418, -0.008179, -0.01978, 0.06299, -0.01123, -0.01941, -0.008667, -0.03223, 0.02075, -0.04517, -0.008667, 0.03247, -0.0001335, -0.007721, -0.002136, 0.004913, -0.01685, -0.008972, -0.03003, 0.01508, 0.02441, -0.006012, -0.005676, -0.02686, -0.0188, -0.04053, -0.01953, 0.01758, 0.02026, 0.002136, 0.01733, 0.002899, -0.052, -0.01294, -0.03613, 0.001205, 0.003021, 0.00705, -0.02332, 0.001297, -0.02502, -0.00174, 0.01904, 0.02417, 0.03394, 0.02319, 0.02515, 0.001297, -0.02979, 0.0177, -0.0354, -0.02686, -0.04688, 0.007324, -0.001419, -0.01489, -0.02075, 0.01495, 0.04248, -0.01831, -0.01172, 0.002487, 0.02734, 0.01123, -0.00531, 0.02734, 0.007996, 0.01892, 0.04297, 0.01007, 0.01337, 0.03271, -0.06079, 0.007812, -0.006989, 0.05249, -0.02002, -0.03442, 0.00589, 0.00209, -0.009644],
  activation: [-0.08447, 1.043, 0.4961, -0.8145, 0.1646, -0.6419, 0.1, -0.8266, -0.4751, 1.33, 0.75, 0.2114, 0.1559, 0.2474, 0.9305, 0.3111, 0.3807, -0.4749, 0.2597, -0.04511, -0.03431, 0.222, 0.2713, -1.401, -0.5853, 0.4476, 0.7045, 0.1586, -1.652, -0.4545, -0.1677, 2.786, 0.09963, -1.051, 0.4476, -1.827, -0.7889, 0.3913, -0.1444, 0.2595, -0.6054, 0.4464, 1.229, 0.06228, 0.03085, 0.9549, 0.8748, -0.0871, 0.3646, 0.5762, -0.02385, -0.5659, -0.1671, -4.197, -0.6841, -0.02287, 5.019, 0.6538, 2.089, 0.593, -0.6393, -0.6553, -1.444, 0.3245, 0.9228, 0.5886, -0.9379, -1.225, 0.1765, 0.162, 1.811, -0.241, -0.1075, -0.04047, 0.05277, 0.3602, 1.464, -1.211, -0.9622, -0.3842, -0.03935, -0.07371, 0.4391, 0.3032, 0.4858, -0.607, 0.9739, -0.6552, 0.5107, -0.02414, -1.746, 0.2008, -1.693, 1.03, -1.132, 0.1503, 0.7677, -0.5614, -0.02231, -0.6225, 0.4661, 0.7397, 0.1026, -1.024, 0.2279, -0.2319, -2.803, -0.7761, -2.606, -0.2217, -0.2597, -0.9727, 1.136, -1.857, 1.307, -1.621, 0.4962, 0.2757, -0.7889, -0.4635, 0.4501, 1.009, -0.2296, -0.3575, 0.4085, -1.336, -0.7467, -1.804, 0.6227, -0.6479, -2.068, -0.1692, 0.08139, 0.0686, -0.742, -0.3576, -0.06363, 0.1458, -0.5169, -0.2162, 1.367, 1.251, -0.1375, 2.083, -5.425, 0.07142, 1.17, -0.6392, 1.142, 0.3375, 0.3916, -0.2, -0.1555, -0.8386, -0.742, 0.4511, -0.5919, -1.148, 0.9567, 0.6253, -0.3721, 0.6055, 0.8445, -2.246, -0.4077, -0.681, -0.4566, -0.3164, 0.9675, 0.5739, -1.217, -0.05721, 1.986, -1.498, 0.917, 0.6066, 0.9836, -0.8702, -0.2391, -0.2056, -0.6519, 0.5923, -0.5437, 0.6863, -0.3741, 1.086, -0.7651, -0.5625, -1.027, 0.0584, -0.1532, 1.831, 1.352, 0.8755, -0.421, 0.0138, -0.04384, -0.1776, 0.4735, -1.037, 1.654, 0.04391, -1.765, -0.05531, -1.361, -0.1323, 0.0131, 0.8821, 5.713, -1.716, -0.2371, -0.09357, 0.4719, 0.9373, -0.9036, 0.155, -0.3628, -1.055, 0.2873, -0.2686, -0.09403, -0.3544, 0.8785, -0.3359, 0.03968, 1.67, -0.118, 0.236, 1.768, 0.464, -0.7248, -0.9834, 0.3332, -0.7462, -1.571, -0.5104, 0.436, -0.4624, 0.6118, 0.112, -2.432, 0.094, -1.071, 1.042, -0.9481, -1.14, -0.6593, -1.298, -0.1454, -1.027, -0.1566, 1.068, 0.8181, 1.066, 0.7688, 0.1573, 0.3527, -0.971, 0.002064, 0.4563, -1.122, -1.022, -1.882, -2.1, 0.4449, -0.6993, 0.2653, 0.2179, 0.6004, 0.1096, 0.683, -0.6704, 0.9707, 0.06514, 0.3925, -3.882, 2.117, 0.9438, -0.1784, -1.631, 0.07087, 0.8348, 0.1195, 1.758, 0.9371, -3.972, -1.304, 1.777, -0.2127, 0.3553, -0.2534, -0.2482, 0.934, 0.6818, 0.1336, 0.04211, 0.3254, -0.1051, 0.6557, -0.09824, 0.1721, 1.213, 0.3178, -1.801, -1.033, 1.437, -0.5982, 1.416, 0.02122, 0.08595, -0.08027, -0.4277, 0.04564, -0.7565, 0.1209, -0.6915, -0.08984, 0.9351, 0.8839, -0.1481, -1.127, -1.156, 0.2364, -0.1247, 0.2316, 0.128, 0.6476, 0.2756, -1.264, 0.4229, -0.2687, 0.2062, -0.8566, 0.5665, 1.987, -0.9187, -1.232, -2.852, 0.01218, 0.9925, -0.1891, 0.8312, 0.6069, 0.8327, -0.4379, -0.7563, 0.5081, 0.7235, -1.035, 0.1561, -0.693, 0.2581, 2.481, 0.5377, 2.061, 1.389, 0.1558, 0.7026, 0.6735, -0.2925, 0.8189, 2.106, 0.6808, -1.237, -0.3574, -0.7052, 0.6751, -0.1876, 0.8834, 0.3888, -0.9463, 0.01933, -0.3415, 0.5937, 1.184, 0.5695, -0.1445, 0.403, -1.112, -0.05472, -0.06945, 3.423, 1.313, -0.2522, 1.11, -0.2752, 6.964, -0.1911, 0.7803, 0.8315, -1.577, 0.1507, 0.3827, 1.168, -1.28, 0.4328, -0.1173, -0.6484, 0.07842, -0.1359, 0.5645, -0.06942, 1.452, -1.01, 0.6062, 0.3694, -1.971, -0.7095, -0.5599, -0.1247, 0.5432, -1.294, -1.458, 0.7423, 0.3599, -0.006019, 0.3336, 0.1423, -0.5031, -0.8025, 0.5045, 0.3279, -0.9455, 1.097, -0.266, 0.4241, -0.01879, 0.711, -0.7367, -0.07749, -0.1211, 1.494, -0.5685, 1.17, -0.02016, 0.5175, -0.7098, -0.8165, -1.136, -1.438, 0.2425, -0.2268, 0.5505, -1.64, -0.07878, -1.744, -1.933, -0.768, -1.106, -1.033, 1.18, 0.4568, 0.6001, -0.5574, -0.3188, 0.5661, -0.09102, 0.352, 0.462, 2.919, -0.5206, 0.2301, -0.391, 0.1743, 0.5601, -1.336, 0.5405, 0.411, 1.173, 1.245, 1.498, 0.09267, -0.08423, 1.01, 0.09545, 1.507, -0.2688, -0.1694, -0.02255, 1.179, -0.1399, -0.642, 0.7192, -3.354, -0.4261, 0.3698, -0.6626, -0.0952, -0.08487, 0.2011, 0.4941, 0.06273, 0.3295, -0.2519, 0.3229, 0.9529, 0.2059, -0.07194, 0.5204, -1.149, -0.8744, -0.5569, 1.304, -0.3407, -0.3677, -0.3838, 0.5958, -0.7599, -0.1135, -0.321, 0.3737, -0.5375, 0.8647, 0.4379, 0.4716, -0.06007, -0.9456, -0.6235, 0.8543, -0.1364, 0.6785, -0.1215, 0.1665, 0.4796, -0.01084, -0.2795, -0.26, -0.00154, 0.5069, -0.1567, -2.526, 0.7499, -0.8028, -0.5312, 0.5233, -0.388, -1.378, 0.96, -0.1703, -1.07, -0.8198, 0.3003, 1.643, 1.188, -1.751, 0.2354, -0.4979, -0.004673, -0.08712, -0.6269, -0.9242, -0.7491, 0.001656, 1.03, -0.4047, 0.4113, 0.2651, 0.3982, 0.7253, -0.03743, 0.3562, -1.108, 0.07853, 0.007802, -0.1006, -0.8198, -0.8342, -0.09016, -0.4776, -0.2063, 6.341, 0.1885, 0.2441, -0.3626, -0.9093, 0.7904, 0.01209, 0.978, -0.3906, 0.03001, 2.404, 0.1632, 0.4108, -0.6416, 0.274, 1.543, 0.6614, 0.7727, -1.97, -1.203, -0.05553, 11.31, -0.8096, -0.1455, -0.7645, -1.613, -0.3584, 1.173, -0.6104, 0.02741, -0.4969, 1.39, -0.3359, 0.4535, -0.2736, 0.1315, -0.1751, -0.5806, 1.972, -0.01164, -0.9381, 0.6348, 0.05466, 0.1376, 0.1821, -1.86, 1.232, -0.06186, 0.03117, -0.186, -0.01836, -0.02127, 0.02078, 0.6765, -5.405, 0.3555, 0.04923, -0.6583, 1.155, 2.345, 0.09403, -0.298, 0.4077, -0.2767, -1.257, -0.8423, -1.38, -0.1652, -0.48, -1.562, -0.7189, 0.6951, 1.156, -0.1883, 0.9608, -0.003142, 7.896, 0.1648, -4.24, -0.3991, 0.1229, 1.912, -0.773, -0.6427, 0.04264, -0.2607, -0.7628, 0.8995, -1.022, 2.107, 0.6019, 2.266, -0.3009, -0.04414, 0.2382, 0.8081, 0.05121, -2.004, 0.8101, -0.8476, 0.3717, 0.03367, -0.5075, -0.4897, 0.4843, 0.651, -0.7253, 0.9877, 0.02913, -0.751, -0.1422, -1.439, 0.5274, 0.7777, 0.9701, -0.1181, 0.9474, 0.2424, -0.416, -1.153, 0.1001, -0.2397, 1.198, -0.6765, 1.857, -0.1792, 0.04466, 0.7897, 1.689, 0.2917, 0.1829, 0.3486, -0.04122, 0.9649, -0.7156, 0.3169, 1.467, 2.113, -0.4345, -0.05001, -0.5654, -0.4219, 1.867, -0.09037, -2.136, -0.4359, -0.5671, -0.5969, -0.7224, -0.01965, 0.005302, 0.08847, -0.8225, -0.02283, -0.4341, -0.5327, 1.286, 0.873, -3.778, 0.02907, 0.501, -0.3231, 0.8145, 0.006065, -0.7272, -0.401, -1.526, 0.342, 0.4259, 0.1565, 0.1905, 1.141, 0.6148, -0.00489, -0.6208, -0.5867, 0.7451, 1.137, -0.5339, 0.1412, -0.3997, -1.226, 0.2899, -0.4463, 0.01273, -1.438, -0.1168, 1.674, 0.301, 0.4327, -0.07216, -0.06415, 0.6546, 0.1798, -1.577, -0.02688, 0.732, 0.6869, -0.301, -0.07204, 0.1906, 1.825, 1.177, -0.3467, 1.013, -1.181, -0.8147, 0.3247, 0.3404, -0.5307, -0.1361, -0.3087, 0.345, 0.8756, 0.4108, 0.3511, 1.191, 0.3837, -0.1339, -0.9399, -0.2517, 0.2087, 0.6972, 0.2151, -0.4011, 1.637, 0.5805, -0.3675, 0.1526, 0.3831, -0.01242, -0.1644, 0.2626, 0.1237, -0.1856, 1.09, -1.74, 0.09722, -0.02222, 0.09655, -0.3143, -0.5442, 1.131, 0.1272, 0.005868, 0.1297, 0.1569, 0.07641, -0.1257, 0.1667, -0.1924, 1.884, -0.5091, 1.09, -0.6555, -0.5137, -0.1611, 0.3785, 0.8427, 0.0003524, -1.341, 0.02713, 1.136, 0.7441, 0.08592, -0.9401, 0.7104, -0.268, 2.387, 1.326, 0.08731, -0.1198, -0.213, -0.426, 0.5931, -1.614, 0.6568, 0.7769, 1.064, 1.131, 0.5612, -0.648, 1.931, -0.3226, -1.237, 0.9024, -0.1212, 1.264, 1.486, 0.798, -0.8582, -0.2321, -0.05119, 1.369, -0.1293, -0.05886, -0.0792, 1.584, 1.774, -0.8002, -0.3015, 1.801, -0.3109, 0.002694, -0.3123, 1.219, 0.8124, 0.05257, 0.003745, -2.062, -0.565, 0.0338, 0.8382, 0.01717, 0.09598, -1.427, 0.5385, -0.4105, 0.6951, 1.132, -0.4954, -0.6738, 0.0372, -0.07796, 0.06925, -0.02384],
};

const N = 896;
type Vec = keyof typeof VECTORS;

// ---------------------------------------------------------------- formats

type Elem = "int4" | "e2m1" | "e4m3";
type ScaleFmt = "fp32" | "fp16" | "e8m0" | "e4m3";
type Preset = "int4-row" | "int4-g128" | "mxfp4" | "nvfp4" | "fp8-row" | "custom";

const roundEven = (a: number) => {
  const f = Math.floor(a), d = a - f;
  return d > 0.5 ? f + 1 : d < 0.5 ? f : f % 2 === 0 ? f : f + 1;
};

// floor(log2 a), exact at powers of two.
function ilog2(a: number): number {
  let E = Math.floor(Math.log2(a));
  if (2 ** E > a) E--;
  if (2 ** (E + 1) <= a) E++;
  return E;
}

// Nearest value of a binary floating-point format with m mantissa bits and
// smallest normal exponent emin (subnormals below it), ties to even,
// saturating at ±max.
function roundFloat(v: number, m: number, emin: number, max: number): number {
  if (v === 0) return 0;
  const a = Math.abs(v);
  const q = 2 ** (Math.max(ilog2(a), emin) - m);
  return Math.sign(v) * Math.min(roundEven(a / q) * q, max);
}
const fp16 = (v: number) => roundFloat(v, 10, -14, 65504);
const e4m3 = (v: number) => roundFloat(v, 3, -6, 448);

// over: half the spacing a next element above q_max would have (8 for INT4
// and E2M1, 480 for E4M3). A value beyond q_max + over is clipped: saturation
// left it farther from x than rounding would have.
interface ElemSpec { bits: number; qmax: number; emax: number; over: number; round(y: number): number }
const ELEM: Record<Elem, ElemSpec> = {
  int4: { bits: 4, qmax: 7, emax: 2, over: 0.5, round: (y) => Math.max(-7, Math.min(7, roundEven(y))) },
  e2m1: { bits: 4, qmax: 6, emax: 2, over: 1, round: (y) => roundFloat(y, 1, 0, 6) },
  e4m3: { bits: 8, qmax: 448, emax: 8, over: 16, round: (y) => e4m3(y) },
};
const SCALE_BITS: Record<ScaleFmt, number> = { fp32: 32, fp16: 16, e8m0: 8, e4m3: 8 };

// Non-negative element values, ascending.
function elementValues(e: Elem): number[] {
  if (e === "int4") return [0, 1, 2, 3, 4, 5, 6, 7];
  if (e === "e2m1") return [0, 0.5, 1, 1.5, 2, 3, 4, 6];
  const out = [0];
  for (let k = 1; k < 8; k++) out.push(k * 2 ** -9);
  for (let E = -6; E <= 8; E++) for (let mm = 0; mm < 8; mm++) { const v = (1 + mm / 8) * 2 ** E; if (v <= 448) out.push(v); }
  return out;
}

const PRESETS: Record<Exclude<Preset, "custom">, { elem: Elem; group: number; scale: ScaleFmt }> = {
  "int4-row": { elem: "int4", group: N, scale: "fp16" },
  "int4-g128": { elem: "int4", group: 128, scale: "fp16" },
  mxfp4: { elem: "e2m1", group: 32, scale: "e8m0" },
  nvfp4: { elem: "e2m1", group: 16, scale: "e4m3" },
  "fp8-row": { elem: "e4m3", group: N, scale: "fp32" },
};
const PRESET_KEYS = Object.keys(PRESETS) as Array<Exclude<Preset, "custom">>;

// ---------------------------------------------------------------- model

interface Group { k: number; start: number; end: number; amax: number; s: number; enc: number; clipped: number; maxErr: number }
interface Result { xhat: number[]; err: number[]; clip: boolean[]; groups: Group[]; rel: number; bEff: number; sT: number; maxErr: number }

function quantize(x: number[], elem: Elem, size: number, sf: ScaleFmt): Result {
  const E = ELEM[elem];
  const amaxT = x.reduce((a, v) => Math.max(a, Math.abs(v)), 0);
  const sT = Math.fround(amaxT / (E.qmax * 448));
  const xhat: number[] = new Array(x.length), err: number[] = new Array(x.length), clip: boolean[] = new Array(x.length);
  const groups: Group[] = [];
  let se = 0, sx = 0, maxErr = 0;
  for (let start = 0, k = 0; start < x.length; start += size, k++) {
    const end = Math.min(x.length, start + size);
    let amax = 0;
    for (let i = start; i < end; i++) amax = Math.max(amax, Math.abs(x[i]));
    let s = 1, enc = 0; // an all-zero group stores s = 1 and zero codes (the chapter's convention)
    if (amax > 0) {
      if (sf === "fp32") s = Math.fround(amax / E.qmax);
      else if (sf === "fp16") s = fp16(amax / E.qmax);
      else if (sf === "e8m0") s = 2 ** (ilog2(amax) - E.emax);
      else { enc = e4m3(amax / E.qmax / sT); s = enc * sT; }
    }
    const limit = s * (E.qmax + E.over);
    let clipped = 0, gErr = 0;
    for (let i = start; i < end; i++) {
      const q = s > 0 ? E.round(x[i] / s) : 0;
      xhat[i] = q * s;
      err[i] = Math.abs(x[i] - xhat[i]);
      clip[i] = Math.abs(x[i]) > limit;
      if (clip[i]) clipped++;
      gErr = Math.max(gErr, err[i]);
      se += err[i] * err[i];
      sx += x[i] * x[i];
    }
    maxErr = Math.max(maxErr, gErr);
    groups.push({ k, start, end, amax, s, enc, clipped, maxErr: gErr });
  }
  return { xhat, err, clip, groups, rel: Math.sqrt(se / sx), bEff: E.bits + SCALE_BITS[sf] / size, sT, maxErr };
}

const memo = new Map<string, Result>();
function result(vec: Vec, elem: Elem, size: number, sf: ScaleFmt): Result {
  const key = `${vec}|${elem}|${size}|${sf}`;
  let r = memo.get(key);
  if (!r) {
    r = quantize(VECTORS[vec], elem, size, sf);
    if (memo.size > 64) memo.clear();
    memo.set(key, r);
  }
  return r;
}

// Error axis of the strip: fixed per vector, so switching formats compares
// like with like. The largest error of any combination the controls reach
// sets it.
const ceilings = new Map<Vec, number>();
function errorCeiling(vec: Vec): number {
  let m = ceilings.get(vec);
  if (m === undefined) {
    m = 0;
    const x = VECTORS[vec];
    for (const e of ["int4", "e2m1", "e4m3"] as Elem[]) for (const size of [16, 32, 128, N]) for (const sf of ["fp32", "fp16", "e8m0", "e4m3"] as ScaleFmt[]) {
      m = Math.max(m, quantize(x, e, size, sf).maxErr);
    }
    ceilings.set(vec, m);
  }
  return m;
}

// ---------------------------------------------------------------- math text

// "_x" or "_{...}" sets a subscript and "^{...}" a superscript as tspans.
interface MRun { s: string; level: number }
function parseMath(src: string, level = 0, out: MRun[] = []): MRun[] {
  const ch = [...src];
  let buf = "";
  const flush = () => { if (buf) { out.push({ s: buf, level }); buf = ""; } };
  for (let i = 0; i < ch.length;) {
    const c = ch[i];
    if ((c === "_" || c === "^") && i + 1 < ch.length) {
      flush();
      const lv = c === "_" ? 1 : -1;
      if (ch[i + 1] === "{") {
        let depth = 1, j = i + 2;
        while (j < ch.length && depth) { if (ch[j] === "{") depth++; else if (ch[j] === "}") depth--; j++; }
        out.push({ s: ch.slice(i + 2, j - 1).join(""), level: lv });
        i = j;
      } else { out.push({ s: ch[i + 1], level: lv }); i += 2; }
    } else { buf += c; i++; }
  }
  flush();
  return out;
}
const subSize = (size: number) => Math.max(TYPE.body, Math.round(size * 0.8));
function mathWidth(src: string, size: number): number {
  return parseMath(src).reduce((a, r) => a + textWidth(r.s, r.level === 0 ? size : subSize(size)), 0);
}
function mtext(x: number, y: number, src: string, size: number, attrs: Record<string, string | number | undefined> = {}): string {
  let cur = 0, inner = "";
  for (const r of parseMath(src)) {
    const off = r.level === 0 ? 0 : r.level < 0 ? -size * 0.38 : size * 0.3;
    const dy = off - cur;
    cur = off;
    inner += `<tspan${dy ? ` dy="${Math.round(dy * 10) / 10}"` : ""}${r.level ? ` font-size="${subSize(size)}"` : ""}>${esc(r.s)}</tspan>`;
  }
  return el("text", { x, y, "font-size": size, ...attrs }, inner);
}

// A wrapping legend whose labels may carry subscripts (lib/legend.ts sets
// plain text only).
type Swatch = { kind: "rect"; fill: string } | { kind: "line"; stroke: string } | { kind: "dot"; fill: string };
function mlegend(items: Array<{ label: string; swatch: Swatch }>, x: number, y: number, maxW: number, size: number = TYPE.body): { svg: string; height: number } {
  const rowH = size + 10;
  let cx = x, row = 0;
  const parts: string[] = [];
  for (const it of items) {
    const w = size + 6 + mathWidth(it.label, size);
    if (cx > x && cx + w > x + maxW) { row++; cx = x; }
    const base = y + row * rowH + size;
    const sw = it.swatch;
    if (sw.kind === "rect") parts.push(el("rect", { x: cx, y: base - size + 2, width: size, height: size - 2, rx: 2, fill: sw.fill }));
    else if (sw.kind === "line") parts.push(el("line", { x1: cx, x2: cx + size, y1: base - size / 2 + 1, y2: base - size / 2 + 1, stroke: sw.stroke, "stroke-width": 2, "stroke-linecap": "round" }));
    else parts.push(el("circle", { cx: cx + size / 2, cy: base - size / 2 + 1, r: size / 2 - 1.5, fill: sw.fill }));
    parts.push(mtext(cx + size + 6, base, it.label, size, { class: "fig-t-muted" }));
    cx += w + 14;
  }
  return { svg: el("g", { class: "fig-legend" }, ...parts), height: (row + 1) * rowH };
}

// ---------------------------------------------------------------- labels

const labels = {
  en: {
    title: "Block-scaled quantization of a real vector",
    act: "Activations entering a query projection",
    weight: "One weight row of the same projection",
    summary: "{vec}: {bits} bits per value, relative error {rel}",
    ovTitle: "The 896 values x_i and each group's range ±q_{max} s_g",
    errTitle: "error |x_i − x̂_i|",
    channel: "channel",
    lgValue: "x_i",
    lgRange: "±q_{max} s_g",
    lgErr: "|x_i − x̂_i|",
    lgClip: "clipped",
    zTitle: "Group {k} of {G}, channels {a} to {b}",
    zTitleAll: "One group, all {n} channels",
    lgStored: "stored x̂_i = s_g q_i",
    lgGrid: "representable s_g q",
    amax: "amax",
    qInt4: "q: the integers −7 to 7",
    qE2m1: "q: 0, ±0.5, ±1, ±1.5, ±2, ±3, ±4, ±6",
    qE4m3: "q: the 253 FP8 E4M3 values up to ±448",
    clipped: "{n} of {g} values clipped to ±q_{max} s_g",
    bitsUnit: "bits per value",
    plusT: "plus one FP32 s_T for the tensor",
    bound: "≤ s_g / 2 = {b}",
    bTitle: "Relative error of the same vector in each named format",
    cur: "current setting",
    bBits: "{b} bits per value",
    "int4-row": "INT4, one FP16 scale",
    "int4-g128": "INT4, g = 128, FP16 scales",
    mxfp4: "MXFP4",
    nvfp4: "NVFP4",
    "fp8-row": "FP8 E4M3, one FP32 scale",
    custom: "current setting",
    describe: "{vec} quantized with {elem} elements in groups of {g} and {scale} scales: {bits} bits per value and a relative error of {rel}. The group holding channel {c} has amax {amax} and scale {s}{clip}.",
    dClip: ", and {n} of its values are clipped",
  },
  zh: {
    title: "真实向量上的块缩放量化",
    act: "进入查询投影的激活",
    weight: "同一投影的一行权重",
    summary: "{vec}：每个值 {bits} 比特，相对误差 {rel}",
    ovTitle: "896 个值 x_i，以及每组的范围 ±q_{max} s_g",
    errTitle: "误差 |x_i − x̂_i|",
    channel: "通道",
    lgValue: "x_i",
    lgRange: "±q_{max} s_g",
    lgErr: "|x_i − x̂_i|",
    lgClip: "被截断",
    zTitle: "第 {k} 组（共 {G} 组），通道 {a} 至 {b}",
    zTitleAll: "只有一组，包含全部 {n} 个通道",
    lgStored: "存储值 x̂_i = s_g q_i",
    lgGrid: "可表示值 s_g q",
    amax: "amax",
    qInt4: "q：−7 到 7 的整数",
    qE2m1: "q：0、±0.5、±1、±1.5、±2、±3、±4、±6",
    qE4m3: "q：最大 ±448 的 253 个 FP8 E4M3 值",
    clipped: "{g} 个值中有 {n} 个被截断到 ±q_{max} s_g",
    bitsUnit: "比特每值",
    plusT: "另加整个张量的一个 FP32 s_T",
    bound: "≤ s_g / 2 = {b}",
    bTitle: "同一向量换用各个命名格式的相对误差",
    cur: "当前设置",
    bBits: "每个值 {b} 比特",
    "int4-row": "INT4，一个 FP16 缩放因子",
    "int4-g128": "INT4，g = 128，FP16 缩放因子",
    mxfp4: "MXFP4",
    nvfp4: "NVFP4",
    "fp8-row": "FP8 E4M3，一个 FP32 缩放因子",
    custom: "当前设置",
    describe: "{vec}按 {elem} 元素、每 {g} 个一组、{scale} 缩放因子量化：每个值 {bits} 比特，相对误差 {rel}。通道 {c} 所在的组 amax 为 {amax}，缩放因子为 {s}{clip}。",
    dClip: "，组内有 {n} 个值被截断",
  },
};
type Labels = typeof labels.en;

const ELEM_NAME: Record<Elem, string> = { int4: "INT4", e2m1: "FP4 E2M1", e4m3: "FP8 E4M3" };
const SCALE_NAME: Record<ScaleFmt, string> = { fp32: "FP32", fp16: "FP16", e8m0: "E8M0", e4m3: "E4M3" };

type P = { vec: Vec; format: Preset; elem: Elem; group: number; scale: ScaleFmt; at: number };

const num = (v: number) => sig(v, 3);
const pctText = (v: number) => `${sig(v * 100, 3)}%`;
const bitsText = (v: number) => (Number.isInteger(v) ? String(v) : Number.isInteger(v * 1000) ? String(v) : fixed(v, 2));

function groupOf(r: Result, at: number): Group {
  return r.groups.find((gr) => at >= gr.start && at < gr.end) ?? r.groups[0];
}

// ---------------------------------------------------------------- panels

// All values with each group's envelope, and the error strip under them.
function renderOverview(p: P, r: Result, x0: number, y0: number, W: number, L: Labels, narrow: boolean): { svg: string; h: number } {
  const parts: string[] = [];
  const x = VECTORS[p.vec];
  const E = ELEM[p.elem];
  const cur = groupOf(r, p.at);
  let y = y0 + 13;
  parts.push(mtext(x0, y, L.ovTitle, TYPE.body, { class: "fig-t-muted" }));
  y += 8;
  const lg = mlegend([
    { label: L.lgValue, swatch: { kind: "rect", fill: C.c1 } },
    { label: L.lgRange, swatch: { kind: "line", stroke: C.c2 } },
    { label: L.lgErr, swatch: { kind: "rect", fill: C.c3 } },
    ...(r.clip.some(Boolean) ? [{ label: L.lgClip, swatch: { kind: "dot" as const, fill: C.bad } }] : []),
  ], x0, y, W);
  parts.push(lg.svg);
  y += lg.height + 6;

  const left = x0 + (narrow ? 40 : 46), right = x0 + W - 4;
  const xs = linear([0, N], [left, right]);
  const pitch = (right - left) / N;
  const H = narrow ? 104 : 124;
  let Y = 0;
  for (const gr of r.groups) Y = Math.max(Y, gr.amax, gr.s * E.qmax);
  const ys = linear([-Y, Y], [y + H, y]);
  const ticks = ys.ticks(4).filter((v) => Math.abs(v) <= Y);
  // Group bands, then the selected group.
  if (r.groups.length > 1) {
    for (const gr of r.groups) if (gr.k % 2 === 1) parts.push(el("rect", { x: xs(gr.start), y, width: xs(gr.end) - xs(gr.start), height: H, fill: C.panel }));
  }
  parts.push(axis({ scale: ys, orient: "left", at: left, ticks, grid: [left, right], size: TYPE.body, format: num }));
  parts.push(el("rect", { x: xs(cur.start), y: y - 2, width: Math.max(2, xs(cur.end) - xs(cur.start)), height: H + 4, fill: C.c1, "fill-opacity": 0.1, stroke: C.ink, "stroke-width": 1.2 }));
  // Values as stems from zero.
  const y0v = ys(0);
  let d = "";
  for (let i = 0; i < N; i++) d += `M${Math.round(xs(i + 0.5) * 10) / 10},${Math.round(y0v * 10) / 10}V${Math.round(ys(x[i]) * 10) / 10}`;
  parts.push(el("path", { d, fill: "none", stroke: C.c1, "stroke-width": Math.max(0.6, Math.min(2, pitch * 0.75)) }));
  // Envelopes ±q_max s_g as steps.
  for (const sgn of [1, -1]) {
    let e = "";
    r.groups.forEach((gr, k) => {
      const yy = Math.round(ys(sgn * gr.s * E.qmax) * 10) / 10;
      e += `${k ? "L" : "M"}${Math.round(xs(gr.start) * 10) / 10},${yy}L${Math.round(xs(gr.end) * 10) / 10},${yy}`;
    });
    parts.push(el("path", { d: e, fill: "none", stroke: C.c2, "stroke-width": 1.5, "stroke-linejoin": "round" }));
  }
  for (let i = 0; i < N; i++) if (r.clip[i]) parts.push(el("circle", { cx: xs(i + 0.5), cy: ys(x[i]), r: 3, fill: C.bad, stroke: C.paper, "stroke-width": 1 }));
  y += H + 10;

  // Error strip on a fixed axis for this vector.
  const eMax = errorCeiling(p.vec);
  const EH = narrow ? 36 : 42;
  y += 14;
  parts.push(mtext(left, y - 4, L.errTitle, TYPE.body, { class: "fig-t-muted" }));
  const es = linear([0, eMax], [y + EH, y]);
  const step = 10 ** Math.floor(Math.log10(eMax));
  parts.push(axis({ scale: es, orient: "left", at: left, ticks: [0, Math.floor(eMax / step) * step], grid: [left, right], size: TYPE.body, format: num }));
  if (r.groups.length > 1) parts.push(el("rect", { x: xs(cur.start), y, width: Math.max(2, xs(cur.end) - xs(cur.start)), height: EH, fill: C.c1, "fill-opacity": 0.1 }));
  d = "";
  for (let i = 0; i < N; i++) if (r.err[i] > 0) d += `M${Math.round(xs(i + 0.5) * 10) / 10},${Math.round(es(0) * 10) / 10}V${Math.round(es(Math.min(eMax, r.err[i])) * 10) / 10}`;
  if (d) parts.push(el("path", { d, fill: "none", stroke: C.c3, "stroke-width": Math.max(0.6, Math.min(2, pitch * 0.75)) }));
  y += EH;
  const chTicks = (narrow ? [0, 256, 512, 768] : [0, 128, 256, 384, 512, 640, 768]).concat([N]);
  parts.push(axis({ scale: xs, orient: "bottom", at: y, ticks: chTicks, size: TYPE.body, title: L.channel, format: (v) => String(v) }));
  y += axisHeight(true, TYPE.body);

  // Every group is a click target that shows it below.
  for (const gr of r.groups) {
    parts.push(el("rect", { x: xs(gr.start), y: y0, width: xs(gr.end) - xs(gr.start), height: y - y0, fill: "transparent", "data-fig-set": `at=${gr.start}`, class: "fig-hit" }));
  }
  return { svg: g({ class: "fig-overview" }, ...parts), h: y - y0 };
}

// The selected group on a number line: each value, the representable points
// s_g·q, and the stored value each one lands on.
function renderGroup(p: P, r: Result, x0: number, y0: number, W: number, L: Labels): { svg: string; h: number } {
  const parts: string[] = [];
  const x = VECTORS[p.vec];
  const E = ELEM[p.elem];
  const gr = groupOf(r, p.at);
  const top = gr.s * E.qmax;
  const R = Math.max(gr.amax, top) * 1.06;
  const xs = linear([-R, R], [x0 + 10, x0 + W - 10]);
  let y = y0 + 14;
  const title = r.groups.length === 1 ? tpl(L.zTitleAll, { n: N }) : tpl(L.zTitle, { k: gr.k + 1, G: r.groups.length, a: gr.start, b: gr.end - 1 });
  parts.push(text(x0, y, title, { "font-size": TYPE.label, class: "fig-t-strong" }));
  y += 30;
  const yTop = y, yAxis = y + 58;
  // Representable points, thinned where they would merge.
  const vals = elementValues(p.elem);
  const pts = [...vals.slice(1).reverse().map((v) => -v), ...vals].map((v) => v * gr.s).filter((v) => Math.abs(v) <= R);
  let last = -Infinity;
  for (const v of pts) {
    const px = xs(v);
    if (px - last < 2) continue;
    last = px;
    parts.push(el("line", { x1: px, x2: px, y1: yAxis - 5, y2: yAxis + 5, stroke: C.ink3, "stroke-width": 1 }));
  }
  parts.push(el("line", { x1: xs(-R), x2: xs(R), y1: yAxis, y2: yAxis, stroke: C.rule, "stroke-width": 1 }));
  for (const sgn of [-1, 1]) parts.push(el("line", { x1: xs(sgn * top), x2: xs(sgn * top), y1: yAxis - 11, y2: yAxis + 11, stroke: C.c2, "stroke-width": 2 }));
  // Values, their path to the stored value, and the stored values.
  const n = gr.end - gr.start;
  const op = n > 64 ? 0.35 : n > 16 ? 0.5 : 0.7;
  let iMax = gr.start;
  for (let i = gr.start; i < gr.end; i++) {
    if (Math.abs(x[i]) > Math.abs(x[iMax])) iMax = i;
    const c = r.clip[i] ? C.bad : C.c1;
    parts.push(el("line", { x1: xs(x[i]), y1: yTop + 7, x2: xs(r.xhat[i]), y2: yAxis - 6, stroke: c, "stroke-width": 1, "stroke-opacity": r.clip[i] ? 0.9 : op }));
    parts.push(el("line", { x1: xs(x[i]), x2: xs(x[i]), y1: yTop - 7, y2: yTop + 7, stroke: c, "stroke-width": 1.5 }));
  }
  const used = new Set<number>();
  for (let i = gr.start; i < gr.end; i++) used.add(r.xhat[i]);
  for (const v of used) parts.push(el("circle", { cx: xs(v), cy: yAxis, r: 3.2, fill: C.c1, stroke: C.paper, "stroke-width": 1 }));
  parts.push(text(xs(x[iMax]), yTop - 11, L.amax, { "font-size": TYPE.body, "text-anchor": "middle", class: "fig-t-halo" }));
  // Ticks at 0 and ±q_max s_g.
  y = yAxis + 11;
  for (const v of [-top, 0, top]) {
    const label = v === 0 ? "0" : (v < 0 ? "−" : "") + num(Math.abs(v));
    parts.push(text(xs(v), y + 13, label, { "font-size": TYPE.body, "text-anchor": v === 0 ? "middle" : v < 0 ? "start" : "end", class: "fig-t-num" }));
  }
  y += 22;
  const lg = mlegend([
    { label: L.lgValue, swatch: { kind: "rect", fill: C.c1 } },
    { label: L.lgStored, swatch: { kind: "dot", fill: C.c1 } },
    { label: L.lgGrid, swatch: { kind: "rect", fill: C.ink3 } },
    { label: L.lgRange, swatch: { kind: "rect", fill: C.c2 } },
  ], x0, y, W);
  parts.push(lg.svg);
  y += lg.height;
  return { svg: g({ class: "fig-group" }, ...parts), h: y - y0 };
}

// The chapter's equations with this group's numbers.
function renderReadout(p: P, r: Result, x0: number, y0: number, W: number, L: Labels, lang: Lang): { svg: string; h: number } {
  const parts: string[] = [];
  const E = ELEM[p.elem];
  const gr = groupOf(r, p.at);
  const lines: Array<{ s: string; cls?: string; size?: number }> = [];
  lines.push({ s: "x̂_i = s_g · q(x_i / s_g)", size: TYPE.title });
  lines.push({ s: p.elem === "int4" ? L.qInt4 : p.elem === "e2m1" ? L.qE2m1 : L.qE4m3, cls: "fig-t-muted" });
  lines.push({ s: `amax = max |x_i| = ${num(gr.amax)}` });
  const q = E.qmax;
  if (p.scale === "fp32") lines.push({ s: `s_g = amax / ${q} = ${num(gr.s)}` });
  else if (p.scale === "fp16") lines.push({ s: `s_g = fp16(amax / ${q}) = ${num(gr.s)}` });
  else if (p.scale === "e8m0") {
    const ea = gr.amax > 0 ? ilog2(gr.amax) : 0;
    lines.push({ s: `s_g = 2^{⌊log₂ amax⌋ − ${E.emax}} = 2^{${ea < 0 ? "−" + -ea : ea} − ${E.emax}} = ${num(gr.s)}` });
  } else {
    lines.push({ s: `s_T = amax_T / (${q} · 448) = ${num(r.sT)}` });
    lines.push({ s: `s_g = e4m3(amax / ${q} / s_T) · s_T = ${num(gr.enc)} s_T = ${num(gr.s)}` });
  }
  const errLine = `max |x_i − x̂_i| = ${num(gr.maxErr)}`;
  if (p.elem === "int4" && gr.clipped === 0) lines.push({ s: `${errLine} ${tpl(L.bound, { b: num(gr.s / 2) })}` });
  else lines.push({ s: errLine });
  if (gr.clipped > 0) lines.push({ s: tpl(L.clipped, { n: gr.clipped, g: gr.end - gr.start }), cls: "fig-t-strong" });
  lines.push({ s: `b_{eff} = ${E.bits} + ${SCALE_BITS[p.scale]} / ${p.group} = ${bitsText(r.bEff)} ${L.bitsUnit}`, cls: "fig-t-strong" });
  if (p.scale === "e4m3") lines.push({ s: L.plusT, cls: "fig-t-muted" });
  lines.push({ s: `‖x − x̂‖ / ‖x‖ = ${pctText(r.rel)}`, cls: "fig-t-strong" });
  let y = y0;
  for (const ln of lines) {
    const size = ln.size ?? TYPE.body;
    // Break a long line at its last " = " that fits.
    const chunks: string[] = [];
    let rest = ln.s;
    while (mathWidth(rest, size) > W) {
      let cut = -1;
      for (let i = rest.lastIndexOf(" = "); i > 0; i = rest.lastIndexOf(" = ", i - 1)) {
        if (mathWidth(rest.slice(0, i), size) <= W) { cut = i; break; }
      }
      if (cut <= 0) {
        const ws = wrap(rest, size, W);
        chunks.push(...ws.slice(0, -1));
        rest = ws[ws.length - 1];
        break;
      }
      chunks.push(rest.slice(0, cut));
      rest = "  " + rest.slice(cut + 1);
    }
    chunks.push(rest);
    for (const c of chunks) {
      y += size + 7;
      parts.push(mtext(x0, y, c, size, { class: `fig-t-num ${ln.cls ?? ""}`.trim() }));
    }
  }
  void lang;
  return { svg: g({ class: "fig-readout" }, ...parts), h: y - y0 + 4 };
}

// Every named format on the same vector: bits per value against error.
function renderCompare(p: P, x0: number, y0: number, W: number, L: Labels): { svg: string; h: number } {
  const parts: string[] = [];
  let y = y0;
  for (const ln of wrap(L.bTitle, TYPE.label, W)) { y += 17; parts.push(text(x0, y, ln, { "font-size": TYPE.label, class: "fig-t-strong" })); }
  y += 3;
  const rows: Array<{ key: Preset; name: string; r: Result }> = PRESET_KEYS.map((k) => ({ key: k, name: L[k], r: result(p.vec, PRESETS[k].elem, PRESETS[k].group, PRESETS[k].scale) }));
  if (p.format === "custom") rows.push({ key: "custom", name: L.cur, r: result(p.vec, p.elem, p.group, p.scale) });
  const eMax = Math.max(...rows.map((rw) => rw.r.rel));
  const valW = 52;
  for (const rw of rows) {
    const on = rw.key === p.format;
    y += 18;
    parts.push(text(x0, y, rw.name, { "font-size": TYPE.body, class: on ? "fig-t-strong" : undefined }));
    parts.push(text(x0 + W, y, tpl(L.bBits, { b: bitsText(rw.r.bEff) }), { "font-size": TYPE.body, "text-anchor": "end", class: `fig-t-num${on ? " fig-t-strong" : " fig-t-muted"}` }));
    y += 6;
    const bw = W - valW;
    parts.push(el("rect", { x: x0, y, width: bw, height: 9, rx: 2, fill: C.panel }));
    parts.push(el("rect", { x: x0, y, width: Math.max(2, (rw.r.rel / eMax) * bw), height: 9, rx: 2, fill: on ? C.c1 : C.ink3 }));
    parts.push(text(x0 + W, y + 9, pctText(rw.r.rel), { "font-size": TYPE.body, "text-anchor": "end", class: `fig-t-num${on ? " fig-t-strong" : ""}` }));
    if (rw.key !== "custom") parts.push(el("rect", { x: x0, y: y - 20, width: W, height: 32, fill: "transparent", "data-fig-set": `format=${rw.key}`, class: "fig-hit" }));
    y += 14;
  }
  return { svg: g({ class: "fig-compare" }, ...parts), h: y - y0 };
}

// ---------------------------------------------------------------- figure

function vecName(p: P, L: Labels): string {
  return p.vec === "activation" ? L.act : L.weight;
}

function describe(st: State<P>, lang: Lang): string {
  const L = labels[lang];
  const p = st.p;
  const r = result(p.vec, p.elem, p.group, p.scale);
  const gr = groupOf(r, p.at);
  return tpl(L.describe, {
    vec: vecName(p, L), elem: ELEM_NAME[p.elem], g: p.group, scale: SCALE_NAME[p.scale],
    bits: bitsText(r.bEff), rel: pctText(r.rel), c: p.at, amax: num(gr.amax), s: num(gr.s),
    clip: gr.clipped ? tpl(L.dClip, { n: gr.clipped }) : "",
  });
}

function render(st: State<P>, lang: Lang): string {
  const L = labels[lang];
  const p = st.p;
  const w = st.w;
  const narrow = w < 480;
  const r = result(p.vec, p.elem, p.group, p.scale);
  const parts: string[] = [];
  let y = 0;
  const name = p.format === "custom" ? `${ELEM_NAME[p.elem]}, g = ${p.group}, ${SCALE_NAME[p.scale]}` : L[p.format];
  const head = `${name} · ${tpl(L.summary, { vec: vecName(p, L), bits: bitsText(r.bEff), rel: pctText(r.rel) })}`;
  for (const ln of wrap(head, TYPE.label, w)) { y += 17; parts.push(text(0, y, ln, { "font-size": TYPE.label, class: "fig-t-strong" })); }
  y += 8;
  const ov = renderOverview(p, r, 0, y, w, L, narrow);
  parts.push(ov.svg);
  y += ov.h + 14;
  const gp = renderGroup(p, r, 0, y, w, L);
  parts.push(gp.svg);
  y += gp.h + 16;
  if (narrow) {
    const ro = renderReadout(p, r, 0, y, w, L, lang);
    parts.push(ro.svg);
    y += ro.h + 16;
    const cp = renderCompare(p, 0, y, w, L);
    parts.push(cp.svg);
    y += cp.h;
  } else {
    const lw = Math.round(w * 0.5);
    const ro = renderReadout(p, r, 0, y, lw, L, lang);
    const cp = renderCompare(p, lw + 24, y, w - lw - 24, L);
    parts.push(ro.svg, cp.svg);
    y += Math.max(ro.h, cp.h);
  }
  return svg(w, y + 6, describe(st, lang), ...parts);
}

export default defineFigure({
  name: "block-scaling",
  title: { en: labels.en.title, zh: labels.zh.title },
  labels,
  params: {
    vec: {
      kind: "choice", label: { en: "Vector", zh: "向量" }, default: "activation",
      options: [
        { value: "activation", label: { en: "Activations", zh: "激活" } },
        { value: "weight", label: { en: "Weights", zh: "权重" } },
      ],
    },
    format: {
      kind: "choice", control: "select", label: { en: "Format", zh: "格式" }, default: "mxfp4",
      options: [
        { value: "int4-row", label: { en: "INT4, one FP16 scale for all 896 values", zh: "INT4，896 个值共用一个 FP16 缩放" } },
        { value: "int4-g128", label: { en: "INT4, groups of 128, FP16 scales", zh: "INT4，每组 128 个，FP16 缩放" } },
        { value: "mxfp4", label: { en: "MXFP4: E2M1, groups of 32, E8M0 scales", zh: "MXFP4：E2M1，每组 32 个，E8M0 缩放" } },
        { value: "nvfp4", label: { en: "NVFP4: E2M1, groups of 16, E4M3 scales", zh: "NVFP4：E2M1，每组 16 个，E4M3 缩放" } },
        { value: "fp8-row", label: { en: "FP8 E4M3, one FP32 scale for all 896 values", zh: "FP8 E4M3，896 个值共用一个 FP32 缩放" } },
        { value: "custom", label: { en: "Another combination", zh: "其他组合" } },
      ],
    },
    elem: {
      kind: "choice", label: { en: "Element", zh: "元素" }, default: "e2m1",
      options: [
        { value: "int4", label: { en: "INT4", zh: "INT4" } },
        { value: "e2m1", label: { en: "FP4 E2M1", zh: "FP4 E2M1" } },
        { value: "e4m3", label: { en: "FP8 E4M3", zh: "FP8 E4M3" } },
      ],
    },
    group: {
      kind: "choice", label: { en: "Group size g", zh: "组大小 g" }, default: 32,
      options: [16, 32, 128, N].map((v) => ({ value: v, label: { en: String(v), zh: String(v) } })),
    },
    scale: {
      kind: "choice", label: { en: "Scale stored as", zh: "缩放因子格式" }, default: "e8m0",
      options: [
        { value: "fp32", label: { en: "FP32", zh: "FP32" } },
        { value: "fp16", label: { en: "FP16", zh: "FP16" } },
        { value: "e8m0", label: { en: "E8M0", zh: "E8M0" } },
        { value: "e4m3", label: { en: "E4M3", zh: "E4M3" } },
      ],
    },
    at: { kind: "range", label: { en: "Show the group of channel", zh: "查看所在组的通道" }, min: 0, max: N - 1, step: 1, default: 591 },
  },
  // A named format sets the element, group size, and scale; changing any of
  // those selects the named format they match, or "another combination".
  update(p, key) {
    if (key === "format") {
      if (p.format === "custom") return p;
      const pr = PRESETS[p.format as Exclude<Preset, "custom">];
      return { ...p, elem: pr.elem, group: pr.group, scale: pr.scale };
    }
    if (key === "elem" || key === "group" || key === "scale") {
      const hit = PRESET_KEYS.find((k) => PRESETS[k].elem === p.elem && PRESETS[k].group === p.group && PRESETS[k].scale === p.scale);
      return { ...p, format: hit ?? "custom" };
    }
    return p;
  },
  render,
  describe,
});
