// A capability horizon read off a fitted success curve, and the published
// horizons it produces across models.
//
// Top panel: the chapter's model Pr(Y = 1 | d) = σ(α − β ln d) with d in
// minutes of human task time, parametrized by the 50 percent horizon h50 and
// the slope β, so α = β ln h50 and the horizon at threshold q is
// h_q = exp((α − logit q) / β) = h50 · exp(−logit q / β). Dragging β pivots
// the curve about (h50, 0.5), which is why the ratio
// h50 / h80 = exp(logit 0.8 / β) depends on the slope alone. h50 and the
// starting β come from a model's published METR fit: the file gives h50 and
// h80 from one logistic fit per model, so β = logit 0.8 / ln(h50 / h80)
// recovers that fit's slope exactly. The dots are illustrative: 48 tasks,
// log-uniform from 1 second to 1 day, eight attempts each, drawn from the
// curve with a seeded generator. They show what a fit sees; the curve is
// the model, not a refit to the dots.
//
// Bottom panel: METR-Horizon-v1.1 per-model 50 and 80 percent horizons by
// release date (data/metr-horizon.ts, generated by
// tools/figure-data/metr-horizon.py). Trend lines are least-squares fits of
// log2 horizon on release date over the models METR flags as the frontier at
// release, inside the chosen window, excluding central 50 percent estimates
// above 16 hours. For the 50 percent series this rule reproduces METR's
// published doubling times (187.8 days for all history, 128.7 from 2023); the
// 80 percent line applies the same rule and is not a METR figure. METR
// publishes only the two thresholds, so this panel does not move with q.

import { defineFigure, type Lang, type State } from "./types.ts";
import { svg, el, text, g, linePath } from "./lib/svg.ts";
import { C, TYPE } from "./lib/theme.ts";
import { linear, log } from "./lib/scale.ts";
import { axis, axisHeight } from "./lib/axis.ts";
import { placeLabels, drawLabels, lineObstacles, overlaps, textBox, textWidth, wrap, type Box, type LabelRequest } from "./lib/labels.ts";
import { fixed, sig, tpl } from "./lib/format.ts";
import { rng } from "./lib/random.ts";
import { logit, sigmoid } from "./lib/stats.ts";
import { wrapCjk } from "./lib/kinsoku.ts";
import { MODELS, CEILING_MIN, type HorizonModel } from "./data/metr-horizon.ts";

// ---------------------------------------------------------------- model

const LOGIT80 = logit(0.8); // ln 4
const TASKS = 48;
const ATTEMPTS = 8;
const TASK_MIN = 1 / 60, TASK_MAX = 1440; // 1 s to 1 day, in minutes
const XA: [number, number] = [0.1 / 60, 7 * 1440]; // 0.1 s to 1 week
const YB: [number, number] = [0.005, 5000];
const DEFAULT_ID = "claude_opus_4_5_inspect";

const BY_ID = new Map(MODELS.map((m) => [m.id, m]));
const betaOf = (m: HorizonModel) => LOGIT80 / Math.log(m.p50[0] / m.p80[0]);
const DEFAULT_MODEL = BY_ID.get(DEFAULT_ID)!;

type Win = "all" | "2023";
type P = { beta: number; q: number; model: string; window: Win; h50: number; seed: number };

// Seeded task times and attempt draws; outcomes are u < p(d), so they move
// monotonically as the curve moves.
const drawMemo = new Map<number, { d: number[]; u: number[][] }>();
function draws(seed: number) {
  const hit = drawMemo.get(seed);
  if (hit) return hit;
  const r = rng(seed);
  const l0 = Math.log(TASK_MIN), l1 = Math.log(TASK_MAX);
  const d: number[] = [], u: number[][] = [];
  for (let i = 0; i < TASKS; i++) {
    d.push(Math.exp(l0 + ((i + r()) / TASKS) * (l1 - l0)));
    u.push(Array.from({ length: ATTEMPTS }, () => r()));
  }
  const out = { d, u };
  drawMemo.set(seed, out);
  return out;
}

const success = (d: number, h50: number, beta: number) => sigmoid(beta * (Math.log(h50) - Math.log(d)));
const horizon = (q: number, h50: number, beta: number) => h50 * Math.exp(-logit(q) / beta);

const dayNum = (iso: string) => {
  const [y, m, d] = iso.split("-").map(Number);
  return Date.UTC(y, m - 1, d) / 86400000;
};

// Which models enter the trend fit: METR's rule inside the chosen window.
function status(m: HorizonModel, win: Win): "fit" | "notFrontier" | "ceiling" | "window" {
  if (!m.frontier) return "notFrontier";
  if (m.p50[0] > CEILING_MIN) return "ceiling";
  if (win === "2023" && m.released < "2023-01-01") return "window";
  return "fit";
}

interface Trend { slope: number; mx: number; my: number; x0: number; x1: number; n: number; days: number }
function trend(win: Win, k: 0 | 1): Trend {
  const pts = MODELS.filter((m) => status(m, win) === "fit").map((m) => [dayNum(m.released), Math.log2((k ? m.p80 : m.p50)[0])] as const);
  const n = pts.length;
  const mx = pts.reduce((s, p) => s + p[0], 0) / n, my = pts.reduce((s, p) => s + p[1], 0) / n;
  const slope = pts.reduce((s, p) => s + (p[0] - mx) * (p[1] - my), 0) / pts.reduce((s, p) => s + (p[0] - mx) ** 2, 0);
  return { slope, mx, my, x0: Math.min(...pts.map((p) => p[0])), x1: Math.max(...pts.map((p) => p[0])), n, days: 1 / slope };
}

// ---------------------------------------------------------------- labels

const MONTHS_EN = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
const ZH_NAMES: Record<string, string> = {
  claude_3_5_sonnet_20240620_inspect: "Claude 3.5 Sonnet（2024 年 6 月）",
  claude_3_5_sonnet_20241022_inspect: "Claude 3.5 Sonnet（2024 年 10 月）",
  claude_mythos_preview_early_inspect: "Claude Mythos Preview（早期版本）",
};
const nameOf = (m: HorizonModel, lang: Lang) => (lang === "zh" ? ZH_NAMES[m.id] ?? m.name : m.name);
function dateOf(iso: string, lang: Lang) {
  const [y, m, d] = iso.split("-").map(Number);
  return lang === "zh" ? `${y} 年 ${m} 月 ${d} 日` : `${d} ${MONTHS_EN[m - 1]} ${y}`;
}

const labels = {
  en: {
    title: "Capability horizon as a fitted threshold",
    headA: "One fitted curve, a horizon at every threshold",
    headB: "Published horizons by release date, METR-Horizon-v1.1",
    legCurve: "σ(α − β ln d)",
    legPub: "published slope, {name}",
    legDots: "simulated task: share of 8 attempts that succeed",
    xA: "human task time d (log scale)",
    yA: "success probability",
    at50: "50%: h₅₀ = {v}",
    at80: "80%: h₈₀ = {v}",
    atQ: "q = {q}: {v}",
    ratio: "h₅₀ / h₈₀ = {r}",
    eqAlpha: "α = β ln h₅₀ = {b} × ln {h} = {a}, with d in minutes",
    eqQ: "q = {q}: logit q = {l}, horizon exp((α − logit q) / β) = {v}",
    eqRatio: "h₅₀ / h₈₀ = exp(logit 0.8 / β) = exp({l8} / {b}) = {r}",
    notePub: "β = {b} is the slope of the published fit for {name}, recovered from its h₅₀ and h₈₀.",
    noteOff: "The published fit for {name} has β = {b} and h₈₀ = {h80}. This curve keeps its h₅₀ and changes only the slope.",
    xB: "release date",
    yB: "horizon in human task time (log scale)",
    p50: "50% horizon",
    p80: "80% horizon",
    notFit: "not in the trend fit",
    ceiling: "16 h: only five tasks are longer",
    sel: "{name}, released {date}",
    fit: "frontier at release, in the trend fit",
    notFrontier: "not the frontier at release, not in the trend fit",
    over: "50% horizon above 16 hours, not in the trend fit",
    window: "released before the fit window",
    original: "Original-suite estimate, not re-run on version 1.1.",
    selVals: "h₅₀ = {h50}, interval {l50} to {u50}; h₈₀ = {h80}, interval {l80} to {u80}",
    selBeta: "h₅₀ / h₈₀ = {r}, so β = logit 0.8 / ln {r} = {b}",
    trend: "Trend over {n} frontier models {win}: the 50% horizon doubles every {d50} days, METR's published fit; the 80% horizon every {d80} days, the same rule applied to the 80% series.",
    winAll: "since 2019",
    win2023: "since 2023",
    describe: "The 50% horizon of {name} is {h50}. With slope β = {b}, the 80% horizon is {h80}, {r} times shorter, and the horizon at q = {q} is {hq}. Across frontier models {win}, the published 50% horizons double every {d50} days and the 80% horizons every {d80} days.",
  },
  zh: {
    title: "能力地平线：拟合得到的阈值",
    headA: "同一条拟合曲线，每个阈值读出一个地平线",
    headB: "METR-Horizon-v1.1：各模型已发布的地平线",
    legCurve: "σ(α − β ln d)",
    legPub: "{name} 的已发布斜率",
    legDots: "模拟任务：8 次尝试中成功的比例",
    xA: "人类完成时间 d（对数刻度）",
    yA: "成功概率",
    at50: "50%：h₅₀ = {v}",
    at80: "80%：h₈₀ = {v}",
    atQ: "q = {q}：{v}",
    ratio: "h₅₀ / h₈₀ = {r}",
    eqAlpha: "α = β ln h₅₀ = {b} × ln {h} = {a}，d 以分钟计",
    eqQ: "q = {q}：logit q = {l}，地平线 exp((α − logit q) / β) = {v}",
    eqRatio: "h₅₀ / h₈₀ = exp(logit 0.8 / β) = exp({l8} / {b}) = {r}",
    notePub: "β = {b} 是 {name} 已发布拟合的斜率，由它的 h₅₀ 与 h₈₀ 反推得到。",
    noteOff: "{name} 的已发布拟合为 β = {b}，h₈₀ = {h80}。这条曲线保留它的 h₅₀，只改变斜率。",
    xB: "发布日期",
    yB: "地平线，以人类完成时间计（对数刻度）",
    p50: "50% 地平线",
    p80: "80% 地平线",
    notFit: "未纳入趋势拟合",
    ceiling: "16 小时：更长的任务只有五项",
    sel: "{name}，发布于 {date}",
    fit: "发布时处于前沿，纳入趋势拟合",
    notFrontier: "发布时不在前沿，未纳入趋势拟合",
    over: "50% 地平线超过 16 小时，未纳入趋势拟合",
    window: "发布早于拟合窗口",
    original: "原始套件的估计，未在 1.1 版上重测。",
    selVals: "h₅₀ = {h50}，区间 {l50} 至 {u50}；h₈₀ = {h80}，区间 {l80} 至 {u80}",
    selBeta: "h₅₀ / h₈₀ = {r}，因此 β = logit 0.8 / ln {r} = {b}",
    trend: "{win}的 {n} 个前沿模型：50% 地平线每 {d50} 天翻一番，即 METR 发布的拟合；80% 地平线每 {d80} 天翻一番，这是对 80% 序列套用同一规则的结果。",
    winAll: "2019 年以来",
    win2023: "2023 年以来",
    describe: "{name} 的 50% 地平线为 {h50}。斜率 β = {b} 时，80% 地平线为 {h80}，短 {r} 倍；q = {q} 时的地平线为 {hq}。{win}的前沿模型中，已发布的 50% 地平线每 {d50} 天翻一番，80% 地平线每 {d80} 天翻一番。",
  },
};

// A duration in minutes, in the largest unit that keeps it above 1.
function dur(min: number, lang: Lang, digits = 3): string {
  const u = lang === "zh" ? ["秒", "分钟", "小时", "天"] : ["s", "min", "h", "d"];
  const [v, i] = min < 1 ? [min * 60, 0] : min < 60 ? [min, 1] : min < 2 * 1440 ? [min / 60, 2] : [min / 1440, 3];
  return `${sig(v, digits)} ${u[i]}`;
}
// A published estimate and its interval, as the chapter quotes them: minutes
// to one decimal, or seconds when the estimate is under a minute.
function pub(t: readonly [number, number, number], lang: Lang): { v: string; lo: string; hi: string } {
  const secs = t[0] < 1;
  const num = (m: number) => (secs ? sig(m * 60, 3) : Number(m.toFixed(1)).toLocaleString("en-US", { minimumFractionDigits: 1, maximumFractionDigits: 1 }));
  const unit = secs ? (lang === "zh" ? "秒" : "s") : (lang === "zh" ? "分钟" : "min");
  return { v: `${num(t[0])} ${unit}`, lo: num(t[1]), hi: num(t[2]) };
}
const tickDur = (lang: Lang) => (v: number) => {
  const T: Array<[number, string, string]> = [[0.1 / 60, "0.1 s", "0.1 秒"], [1 / 60, "1 s", "1 秒"], [1 / 6, "10 s", "10 秒"], [1, "1 min", "1 分钟"], [10, "10 min", "10 分钟"], [60, "1 h", "1 小时"], [600, "10 h", "10 小时"], [1440, "1 d", "1 天"], [10080, "1 wk", "1 周"]];
  const hit = T.find((t) => Math.abs(t[0] / v - 1) < 1e-6);
  return hit ? (lang === "zh" ? hit[2] : hit[1]) : dur(v, lang);
};
const pctq = (q: number) => { const v = Math.round(q * 1000) / 10; return `${fixed(v, v % 1 ? 1 : 0)}%`; };

function describe(st: State<P>, lang: Lang): string {
  const L = labels[lang];
  const p = st.p;
  const m = BY_ID.get(p.model) ?? DEFAULT_MODEL;
  const t50 = trend(p.window, 0), t80 = trend(p.window, 1);
  return tpl(L.describe, {
    name: nameOf(m, lang), h50: dur(p.h50, lang), b: fixed(p.beta, 2), h80: dur(horizon(0.8, p.h50, p.beta), lang),
    r: sig(Math.exp(LOGIT80 / p.beta), 3), q: pctq(p.q), hq: dur(horizon(p.q, p.h50, p.beta), lang),
    win: p.window === "all" ? L.winAll : L.win2023, d50: fixed(t50.days, 1), d80: fixed(t80.days, 1),
  });
}

// ---------------------------------------------------------------- render

function lines(s: string, lang: Lang, fs: number, w: number) {
  return lang === "zh" ? wrapCjk(s, fs, w) : wrap(s, fs, w);
}

function render(st: State<P>, lang: Lang): string {
  const L = labels[lang];
  const p = st.p;
  const w = st.w;
  const narrow = w < 480;
  const fs = TYPE.body;
  const m = BY_ID.get(p.model) ?? DEFAULT_MODEL;
  const bPub = betaOf(m);
  const onPub = Math.abs(p.beta - bPub) < 1e-6 && Math.abs(p.h50 - m.p50[0]) < 1e-9;
  const parts: string[] = [];
  const left = narrow ? 40 : 46, right = narrow ? 6 : 12;

  // ================= panel A: the success curve
  let y = 0;
  for (const ln of lines(L.headA, lang, TYPE.label, w)) { y += 18; parts.push(text(0, y - 2, ln, { "font-size": TYPE.label, class: "fig-t-strong" })); }
  y += 10;
  // Legend: curve, published curve (when the slope differs), dots.
  {
    const items: Array<{ label: string; draw: (x: number, yy: number) => string }> = [
      { label: L.legCurve, draw: (x, yy) => el("line", { x1: x, x2: x + 18, y1: yy - 4, y2: yy - 4, stroke: C.c1, "stroke-width": 2.5 }) },
    ];
    if (!onPub) items.push({ label: tpl(L.legPub, { name: nameOf(m, lang) }), draw: (x, yy) => el("line", { x1: x, x2: x + 18, y1: yy - 4, y2: yy - 4, stroke: C.ink2, "stroke-width": 1.5, "stroke-dasharray": "4 3" }) });
    items.push({ label: L.legDots, draw: (x, yy) => el("circle", { cx: x + 9, cy: yy - 4, r: 3.5, fill: C.ink2, "fill-opacity": 0.55 }) });
    let cx = 0, row = 0;
    for (const it of items) {
      const iw = 24 + textWidth(it.label, fs);
      if (cx > 0 && cx + iw > w) { cx = 0; row++; }
      const yy = y + 14 + row * 20;
      parts.push(it.draw(cx, yy), text(cx + 24, yy, it.label, { "font-size": fs, class: "fig-t-muted" }));
      cx += iw + 16;
    }
    y += 14 + row * 20 + 16;
  }
  const topA = y + 14;
  const hA = narrow ? 190 : 220;
  // Keep the last time label ("1 wk") inside the figure.
  const rightA = Math.max(right, Math.ceil(textWidth(tickDur(lang)(XA[1]), fs) / 2) + 2);
  const xa = log(XA, [left, w - rightA]);
  const ya = linear([0, 1], [topA + hA, topA]);
  parts.push(axis({ scale: xa, orient: "bottom", at: topA + hA, grid: [topA, topA + hA], ticks: [1 / 60, 1, 60, 1440, 10080], format: tickDur(lang), title: L.xA, size: fs }));
  parts.push(axis({ scale: ya, orient: "left", at: left, grid: [left, w - rightA], ticks: [0, 0.2, 0.5, 0.8, 1], format: (v) => `${Math.round(v * 100)}%`, title: L.yA, size: fs }));

  // Simulated outcomes.
  // Label obstacles are the curve and the guide lines; labels carry a halo,
  // so they may sit over a dot.
  const dr = draws(p.seed);
  const obstacles: Box[] = [];
  for (let i = 0; i < TASKS; i++) {
    const pr = success(dr.d[i], p.h50, p.beta);
    const k = dr.u[i].filter((u) => u < pr).length;
    parts.push(el("circle", { cx: xa(dr.d[i]), cy: ya(k / ATTEMPTS), r: narrow ? 2.6 : 3.2, fill: C.ink2, "fill-opacity": 0.5 }));
  }
  // Curves: the published fit (dashed, when the slope has moved) and the chosen one.
  const curvePts = (beta: number) => {
    const n = 160, l0 = Math.log(XA[0]), l1 = Math.log(XA[1]);
    return Array.from({ length: n + 1 }, (_, i) => {
      const d = Math.exp(l0 + (i / n) * (l1 - l0));
      return [xa(d), ya(success(d, p.h50, beta))] as [number, number];
    });
  };
  if (!onPub) parts.push(el("path", { d: linePath(curvePts(bPub)), fill: "none", stroke: C.ink2, "stroke-width": 1.5, "stroke-dasharray": "4 3" }));
  const main = curvePts(p.beta);
  parts.push(el("path", { d: linePath(main), fill: "none", stroke: C.c1, "stroke-width": 2.5, "stroke-linejoin": "round" }));
  obstacles.push(...lineObstacles(main, 6, 3));

  // Read-offs at 50%, 80%, and q: a guide across the plot at that success
  // level, a dot where it meets the curve, and a drop to the time axis. Each
  // label sits at either end of its guide, above or below it, wherever it
  // clears the curve and the other guides.
  const h50 = p.h50, h80 = horizon(0.8, h50, p.beta), hq = horizon(p.q, h50, p.beta);
  const near = (a: number, b: number) => Math.abs(a - b) < 1e-9;
  const reads: Array<{ q: number; h: number; label: string; strong: boolean }> = [
    { q: 0.5, h: h50, label: tpl(L.at50, { v: dur(h50, lang) }), strong: near(p.q, 0.5) },
    { q: 0.8, h: h80, label: tpl(L.at80, { v: dur(h80, lang) }), strong: near(p.q, 0.8) },
  ];
  if (!near(p.q, 0.5) && !near(p.q, 0.8)) reads.push({ q: p.q, h: hq, label: tpl(L.atQ, { q: pctq(p.q), v: dur(hq, lang) }), strong: true });
  const xEnd = w - rightA;
  const guides: Box[][] = [];
  for (const r of reads) {
    const yy = ya(r.q);
    const inside = r.h >= XA[0];
    const xx = inside ? xa(r.h) : left;
    const col = r.strong ? C.c2 : C.ink2;
    const sw = r.strong ? 1.5 : 1;
    parts.push(el("line", { x1: left, x2: xEnd, y1: yy, y2: yy, stroke: col, "stroke-width": sw, "stroke-dasharray": "4 3" }));
    if (inside) {
      parts.push(el("line", { x1: xx, x2: xx, y1: yy, y2: topA + hA, stroke: col, "stroke-width": sw, "stroke-dasharray": "4 3" }));
      parts.push(el("circle", { cx: xx, cy: yy, r: 4, fill: col, stroke: C.paper, "stroke-width": 1.5 }));
      parts.push(el("path", { d: `M${xx - 4},${topA + hA}L${xx + 4},${topA + hA}L${xx},${topA + hA - 6}Z`, fill: col }));
    } else {
      // Off the axis to the left: an arrow at the edge.
      parts.push(el("path", { d: `M${left + 1},${yy}L${left + 8},${yy - 4}L${left + 8},${yy + 4}Z`, fill: col }));
    }
    guides.push(lineObstacles([[left, yy], [xEnd, yy]], 8, 1));
  }
  const dropped: typeof reads = [];
  {
    const taken: Box[] = [...obstacles];
    const order = reads.map((r, i) => ({ r, i })).sort((a, b) => Number(b.r.strong) - Number(a.r.strong) || b.r.q - a.r.q);
    for (const { r, i } of order) {
      const yy = ya(r.q);
      const others = guides.filter((_, j) => j !== i).flat();
      const cands: Array<[number, number, "start" | "end"]> = [
        [xEnd - 2, yy - 5, "end"], [left + 12, yy - 5, "start"], [xEnd - 2, yy + 5 + fs * 0.78, "end"], [left + 12, yy + 5 + fs * 0.78, "start"],
      ];
      let done = false;
      for (const [tx, ty, anchor] of cands) {
        const box = textBox(tx, ty, r.label, fs, anchor);
        if (box.y0 < topA - 4 || box.y1 > topA + hA - 2 || box.x0 < left + 2 || box.x1 > xEnd) continue;
        if ([...taken, ...others].some((b) => overlaps(b, box))) continue;
        parts.push(text(tx, ty, r.label, { "font-size": fs, "text-anchor": anchor, class: `fig-t-halo fig-t-num${r.strong ? " fig-t-strong" : ""}` }));
        taken.push(box);
        done = true;
        break;
      }
      if (!done) dropped.push(r);
    }
  }

  // The ratio h50 / h80, as a bracket under the time axis.
  y = topA + hA + axisHeight(true, fs) + 10;
  {
    const r = Math.exp(LOGIT80 / p.beta);
    const x80 = Math.max(left, xa(Math.max(h80, XA[0]))), x50 = xa(h50);
    parts.push(el("path", { d: `M${x80},${y - 6}L${x80},${y}L${x50},${y}L${x50},${y - 6}`, fill: "none", stroke: C.ink2, "stroke-width": 1.25 }));
    const lab = tpl(L.ratio, { r: sig(r, 3) });
    const tw = textWidth(lab, fs);
    const cx = Math.min(w - tw / 2, Math.max(tw / 2, (x80 + x50) / 2));
    parts.push(text(cx, y + fs + 5, lab, { "font-size": fs, "text-anchor": "middle", class: "fig-t-num fig-t-strong" }));
    y += fs + 5 + 22;
  }
  // Read-offs that found no room beside their guide are listed here, each
  // with its guide's line style.
  for (const r of dropped) {
    parts.push(el("line", { x1: 0, x2: 16, y1: y - 4, y2: y - 4, stroke: r.strong ? C.c2 : C.ink2, "stroke-width": 1.5, "stroke-dasharray": "4 3" }));
    parts.push(text(22, y, r.label, { "font-size": fs, class: `fig-t-num${r.strong ? " fig-t-strong" : ""}` }));
    y += 18;
  }
  if (dropped.length) y += 8;

  // Readout: the equation's terms.
  {
    const rp: string[] = [];
    const alpha = p.beta * Math.log(h50);
    const rows = [
      tpl(L.eqAlpha, { b: fixed(p.beta, 2), h: sig(h50, 4), a: fixed(alpha, 2) }),
      tpl(L.eqQ, { q: pctq(p.q), l: fixed(logit(p.q), 2), v: dur(hq, lang) }),
      tpl(L.eqRatio, { l8: fixed(LOGIT80, 3), b: fixed(p.beta, 2), r: sig(Math.exp(LOGIT80 / p.beta), 3) }),
    ];
    for (const row of rows) for (const ln of lines(row, lang, fs, w)) { rp.push(text(0, y, ln, { "font-size": fs, class: "fig-t-num" })); y += 17; }
    y += 4;
    const note = onPub ? tpl(L.notePub, { b: fixed(bPub, 2), name: nameOf(m, lang) })
      : tpl(L.noteOff, { name: nameOf(m, lang), b: fixed(bPub, 2), h80: pub(m.p80, lang).v });
    for (const ln of lines(note, lang, fs, w)) { rp.push(text(0, y, ln, { "font-size": fs, class: "fig-t-muted" })); y += 17; }
    parts.push(g({ class: "fig-readout" }, ...rp));
  }

  // ================= panel B: published horizons by release date
  y += 8;
  for (const ln of lines(L.headB, lang, TYPE.label, w)) { y += 18; parts.push(text(0, y, ln, { "font-size": TYPE.label, class: "fig-t-strong" })); }
  y += 12;
  // Legend.
  {
    const items: Array<{ label: string; draw: (x: number, yy: number) => string }> = [
      { label: L.p50, draw: (x, yy) => el("circle", { cx: x + 6, cy: yy - 4, r: 4, fill: C.c1 }) },
      { label: L.p80, draw: (x, yy) => el("path", { d: diamond(x + 6, yy - 4, 5), fill: C.c2 }) },
      { label: L.notFit, draw: (x, yy) => el("circle", { cx: x + 6, cy: yy - 4, r: 3.5, fill: C.paper, stroke: C.ink2, "stroke-width": 1.5 }) },
    ];
    let cx = 0, row = 0;
    for (const it of items) {
      const iw = 18 + textWidth(it.label, fs);
      if (cx > 0 && cx + iw > w) { cx = 0; row++; }
      const yy = y + 14 + row * 20;
      parts.push(it.draw(cx, yy), text(cx + 18, yy, it.label, { "font-size": fs, class: "fig-t-muted" }));
      cx += iw + 16;
    }
    y += 14 + row * 20 + 16;
  }
  const topB = y + 14;
  // The time labels on this axis are wider than percentages, and wider in zh.
  const ticksB = [1 / 60, 1, 60, 600];
  const leftB = Math.max(left, Math.ceil(Math.max(...ticksB.map((v) => textWidth(tickDur(lang)(v), fs)))) + 12);
  const hB = narrow ? 230 : 260;
  const x0 = dayNum("2019-01-01"), x1 = dayNum("2026-07-01");
  const xb = linear([x0, x1], [leftB + 6, w - right - 6]);
  const yb = log(YB, [topB + hB, topB]);
  const years = Array.from({ length: 8 }, (_, i) => dayNum(`${2019 + i}-01-01`));
  parts.push(axis({ scale: xb, orient: "bottom", at: topB + hB, grid: [topB, topB + hB], ticks: years, format: (v) => String(new Date(v * 86400000).getUTCFullYear()), title: L.xB, size: fs }));
  parts.push(axis({ scale: yb, orient: "left", at: leftB, grid: [leftB, w - right], ticks: ticksB, minor: true, format: tickDur(lang), title: L.yB, size: fs }));
  const obsB: Box[] = [];

  // The 16-hour ceiling.
  const yc = yb(CEILING_MIN);
  parts.push(el("line", { x1: leftB, x2: w - right, y1: yc, y2: yc, stroke: C.ink3, "stroke-width": 1.25, "stroke-dasharray": "6 3" }));
  obsB.push(...lineObstacles([[leftB, yc], [w - right, yc]], 8, 1));

  // Trend lines.
  const tr = [trend(p.window, 0), trend(p.window, 1)] as const;
  const emph = [Math.abs(p.q - 0.5) < 1e-9, Math.abs(p.q - 0.8) < 1e-9];
  for (const k of [0, 1] as const) {
    const t = tr[k];
    const ptsT: Array<[number, number]> = [t.x0, t.x1].map((xx) => [xb(xx), yb(2 ** (t.my + t.slope * (xx - t.mx)))]);
    parts.push(el("path", { d: linePath(ptsT), stroke: k ? C.c2 : C.c1, "stroke-width": emph[k] ? 2.5 : 1.75, "stroke-opacity": 0.85, fill: "none" }));
    obsB.push(...lineObstacles(ptsT, 6, 2));
  }

  // Interval bars for the 50% series, then the points.
  for (const mm of MODELS) {
    const cx = xb(dayNum(mm.released));
    const [, lo, hi] = mm.p50;
    parts.push(el("line", { x1: cx, x2: cx, y1: yb(Math.max(YB[0], lo)), y2: yb(Math.min(YB[1], hi)), stroke: C.c1, "stroke-opacity": 0.3, "stroke-width": 1 }));
  }
  const sel = m;
  for (const k of [1, 0] as const) {
    for (const mm of MODELS) {
      const v = (k ? mm.p80 : mm.p50)[0];
      const cx = xb(dayNum(mm.released)), cy = yb(v);
      const inFit = status(mm, p.window) === "fit";
      const col = k ? C.c2 : C.c1;
      const shape = k
        ? el("path", { d: diamond(cx, cy, 5), fill: inFit ? col : C.paper, stroke: col, "stroke-width": 1.5 })
        : el("circle", { cx, cy, r: 4, fill: inFit ? col : C.paper, stroke: col, "stroke-width": 1.5 });
      parts.push(g({ "data-fig-set": `model=${mm.id}`, class: "fig-hit" }, el("circle", { cx, cy, r: 8, fill: "transparent" }), shape));
      obsB.push({ x0: cx - 5, y0: cy - 5, x1: cx + 5, y1: cy + 5 });
    }
  }
  // The chosen model: both intervals, a connector, and a ring.
  {
    const cx = xb(dayNum(sel.released));
    for (const [k, trip] of [[0, sel.p50], [1, sel.p80]] as const) {
      parts.push(el("line", { x1: cx, x2: cx, y1: yb(Math.max(YB[0], trip[1])), y2: yb(Math.min(YB[1], trip[2])), stroke: k ? C.c2 : C.c1, "stroke-width": 2 }));
      for (const v of [trip[1], trip[2]]) if (v > YB[0] && v < YB[1]) parts.push(el("line", { x1: cx - 4, x2: cx + 4, y1: yb(v), y2: yb(v), stroke: k ? C.c2 : C.c1, "stroke-width": 2 }));
    }
    for (const v of [sel.p50[0], sel.p80[0]]) parts.push(el("circle", { cx, cy: yb(v), r: 8, fill: "none", stroke: C.ink, "stroke-width": 1.5 }));
  }
  // Labels: the chosen model, landmarks, and the ceiling.
  {
    const marks = new Set([sel.id, "gpt2", "gpt_4", "claude_mythos_preview_early_inspect"]);
    const reqB: LabelRequest[] = [];
    for (const mm of MODELS) {
      if (!marks.has(mm.id)) continue;
      const isSel = mm.id === sel.id;
      reqB.push({ x: xb(dayNum(mm.released)), y: yb(mm.p50[0]), text: nameOf(mm, lang), size: fs,
        sides: ["above-left", "left", "above", "below-left", "above-right", "right", "below-right"], gap: 10, priority: isSel ? 5 : 2,
        attrs: { class: `fig-t-halo${isSel ? " fig-t-strong" : " fig-t-muted"}` } });
    }
    reqB.push({ x: leftB + 4, y: yc, text: L.ceiling, size: fs, sides: ["above-right", "below-right"], gap: 4, priority: 4, attrs: { class: "fig-t-halo fig-t-muted" } });
    const pl = placeLabels(reqB, { x0: leftB + 2, y0: topB + 2, x1: w - right, y1: topB + hB - 2 }, obsB);
    parts.push(drawLabels(pl.placed));
  }

  // Readout: the chosen model's published values and the trend.
  y = topB + hB + axisHeight(true, fs) + 16;
  {
    const rp: string[] = [];
    const s = status(sel, p.window);
    const head = `${tpl(L.sel, { name: nameOf(sel, lang), date: dateOf(sel.released, lang) })}${lang === "zh" ? "；" : "; "}${s === "fit" ? L.fit : s === "notFrontier" ? L.notFrontier : s === "ceiling" ? L.over : L.window}`;
    for (const ln of lines(head, lang, fs, w)) { rp.push(text(0, y, ln, { "font-size": fs, class: "fig-t-strong" })); y += 17; }
    if (sel.originalSuite) for (const ln of lines(L.original, lang, fs, w)) { rp.push(text(0, y, ln, { "font-size": fs, class: "fig-t-muted" })); y += 17; }
    const r = sel.p50[0] / sel.p80[0];
    const vals = [
      (() => { const a = pub(sel.p50, lang), b = pub(sel.p80, lang); return tpl(L.selVals, { h50: a.v, l50: a.lo, u50: a.hi, h80: b.v, l80: b.lo, u80: b.hi }); })(),
      tpl(L.selBeta, { r: fixed(r, 2), b: fixed(betaOf(sel), 2) }),
    ];
    for (const row of vals) for (const ln of lines(row, lang, fs, w)) { rp.push(text(0, y, ln, { "font-size": fs, class: "fig-t-num" })); y += 17; }
    y += 6;
    const tl = tpl(L.trend, { n: tr[0].n, win: p.window === "all" ? L.winAll : L.win2023, d50: fixed(tr[0].days, 1), d80: fixed(tr[1].days, 1) });
    for (const ln of lines(tl, lang, fs, w)) { rp.push(text(0, y, ln, { "font-size": fs, class: "fig-t-muted" })); y += 17; }
    parts.push(g({ class: "fig-readout" }, ...rp));
  }
  return svg(w, y, describe(st, lang), ...parts);
}

function diamond(cx: number, cy: number, r: number): string {
  return `M${cx},${cy - r}L${cx + r},${cy}L${cx},${cy + r}L${cx - r},${cy}Z`;
}

export default defineFigure({
  name: "horizon-threshold",
  title: { en: labels.en.title, zh: labels.zh.title },
  labels,
  params: {
    q: {
      kind: "range", label: { en: "Success threshold q", zh: "成功阈值 q" }, min: 0.5, max: 0.99, step: 0.01, default: 0.8,
      marks: [{ value: 0.5, label: { en: "50%", zh: "50%" } }, { value: 0.8, label: { en: "80%", zh: "80%" } }],
    },
    beta: { kind: "range", label: { en: "Slope β of the curve", zh: "曲线斜率 β" }, min: 0.3, max: 2, step: 0.01, default: betaOf(DEFAULT_MODEL) },
    model: {
      kind: "choice", label: { en: "Model (METR fit)", zh: "模型（METR 拟合）" }, default: DEFAULT_ID, control: "select",
      options: MODELS.map((mm) => ({ value: mm.id, label: { en: mm.name, zh: nameOf(mm, "zh") } })),
    },
    window: {
      kind: "choice", label: { en: "Trend fit window", zh: "趋势拟合窗口" }, default: "2023",
      options: [
        { value: "all", label: { en: "All models since 2019", zh: "2019 年以来全部模型" } },
        { value: "2023", label: { en: "Models since 2023", zh: "2023 年以来的模型" } },
      ],
    },
    h50: { kind: "range", scale: "log", label: { en: "50% horizon h₅₀ (minutes)", zh: "50% 地平线 h₅₀（分钟）" }, min: 0.01, max: 5000, default: DEFAULT_MODEL.p50[0], control: false },
    seed: { kind: "range", label: { en: "Seed of the simulated outcomes", zh: "模拟结果的随机种子" }, min: 1, max: 1000, step: 1, default: 7, control: false },
  },
  // Choosing a model loads its published fit: its h50 and the slope recovered
  // from its h50 and h80. The slope slider then explores other slopes at the
  // same h50.
  update(p, key) {
    if (key === "model") {
      const m = BY_ID.get(p.model);
      if (m) return { ...p, h50: m.p50[0], beta: Math.min(2, Math.max(0.3, betaOf(m))) };
    }
    return p;
  },
  render,
  describe,
});
