// A reference architecture for the stack a model builder runs, by layer: the
// data plane (sources and rights, extraction and filtering, tokenization and
// mixture, the shard store, and post-training data), the training runtime with
// its checkpoint store and experiment tracker, the RL post-training loop
// (rollout engines, the environment fleet, rewards and verifiers), the
// evaluation gate and release, and compute. Arrows are hand-offs; each arrow's
// color is what the hand-off carries: data, weights, trajectories and rewards,
// or evidence (metrics and evaluation results). The figure answers where each
// kind of artifact travels: data moves one way into the trainer, weights leave
// the trainer for three destinations (the checkpoint store, the rollout
// engines, and, through the gate, release), and trajectories return to the
// trainer only through the rewards and verifiers.
//
// Selecting a component shows what it does, example projects, the section of
// the chapter that covers it, and each hand-off in and out. With nothing
// selected, the readout groups every hand-off by what it carries.
//
// The components and hand-offs restate the chapter's prose. The example
// projects are illustrative, not recommendations, and were checked on 25
// September 2026 against each project's own repository or documentation; the
// chapter's dated blocks cite them:
// - data: github.com/huggingface/datatrove, github.com/NVIDIA-NeMo/Curator,
//   github.com/mosaicml/streaming, Megatron-LM's weighted --data-path
// - runtime and checkpoints: github.com/NVIDIA/Megatron-LM (CheckpointConfig),
//   github.com/pytorch/torchtitan, github.com/deepspeedai/DeepSpeed,
//   github.com/AI-Hypercomputer/maxtext, PyTorch Distributed Checkpoint,
//   github.com/google/orbax
// - RL: github.com/verl-project/verl, github.com/OpenRLHF/OpenRLHF,
//   github.com/NVIDIA-NeMo/RL, github.com/NovaSky-AI/SkyRL,
//   github.com/PrimeIntellect-ai/prime-rl, github.com/THUDM/slime,
//   github.com/areal-project/AReaL; the vLLM weight-transfer API
//   (vllm.ai/blog/2026-05-28-native-rl-apis) and SGLang's RL endpoints
// - environments: github.com/huggingface/OpenEnv,
//   github.com/PrimeIntellect-ai/verifiers, SkyRL-Gym, github.com/huggingface/Math-Verify
// - gate and release: github.com/EleutherAI/lm-evaluation-harness, Inspect,
//   safetensors, the OpenSSF model signing specification
// - compute: Slurm 26.05, Kueue (Topology Aware Scheduling), JobSet

import { defineFigure, type Lang, type State, type Text } from "./types.ts";
import { svg, el, text, g } from "./lib/svg.ts";
import { C, TYPE } from "./lib/theme.ts";
import { textWidth } from "./lib/labels.ts";
import { wrapLines } from "./lib/wrap-lines.ts";
import { tpl } from "./lib/format.ts";

// ---------------------------------------------------------------- model

type Id =
  | "sources" | "process" | "tokenize" | "shards" | "ptdata"
  | "trainer" | "ckpt" | "tracking"
  | "rollout" | "reward" | "envs"
  | "gate" | "release"
  | "scheduler" | "accel";
type Layer = "data" | "runtime" | "rl" | "gates" | "compute";
type Section = "data" | "job" | "ckpt" | "rollout" | "env" | "gate" | "release";
type Kind = "data" | "weights" | "rollouts" | "evidence";

interface Comp {
  id: Id;
  layer: Layer;
  name: Text;
  examples: Text; // short list drawn in the box
  more: Text; // the readout's example line
  does: Text;
  section: Section;
}

const COMPS: readonly Comp[] = [
  {
    id: "sources", layer: "data",
    name: { en: "Sources and rights", zh: "数据来源与权利" },
    examples: { en: "web crawls, licensed corpora, code, synthetic data", zh: "网页抓取、授权语料、代码、合成数据" },
    more: { en: "Common Crawl snapshots, licensed books and news, permissively licensed code, and text generated by a teacher model, each with a source ID, the terms it came under, and its opt-out status.", zh: "Common Crawl 快照、授权图书与新闻、宽松许可的代码，以及教师模型生成的文本；每一份都带有来源标识、获取时的条款和退出状态。" },
    does: { en: "Decides which sources may enter. Every document keeps its source ID and terms, so a later audit or deletion request can find everything it reached.", zh: "决定哪些来源可以进入。每份文档都保留来源标识和条款，日后审计或处理删除请求时，能找到它影响到的所有产物。" },
    section: "data",
  },
  {
    id: "process", layer: "data",
    name: { en: "Extraction and filtering", zh: "抽取与过滤" },
    examples: { en: "extraction, dedup, quality and PII filters", zh: "抽取、去重、质量与个人信息过滤" },
    more: { en: "DataTrove pipelines on Slurm or Ray, or NeMo Curator's GPU pipelines on Ray: HTML-to-text extraction, language identification, exact and MinHash deduplication, classifier quality filters, PII redaction, and decontamination against evaluation sets.", zh: "在 Slurm 或 Ray 上运行的 DataTrove 流水线，或在 Ray 上运行的 NeMo Curator GPU 流水线：HTML 转文本、语言识别、精确去重与 MinHash 去重、分类器质量过滤、个人信息脱敏，以及针对评测集的去污染。" },
    does: { en: "Turns raw documents into accepted text: extracts it, removes near-duplicates, scores quality, redacts personal data, and removes evaluation items. Each filter is versioned, because its thresholds define the corpus.", zh: "把原始文档变成被接受的文本：抽取正文、去掉近重复、给质量打分、脱敏个人信息、剔除评测题目。每个过滤器都有版本号，因为它的阈值决定了语料是什么。" },
    section: "data",
  },
  {
    id: "tokenize", layer: "data",
    name: { en: "Tokenize and mix", zh: "分词与配比" },
    examples: { en: "pinned tokenizer, mixture weights per phase", zh: "固定的分词器、按阶段设定的配比" },
    more: { en: "A pinned tokenizer turns accepted text into token IDs; mixture weights per source and per phase, such as the weighted prefix lists Megatron-LM reads, set how many tokens each source contributes.", zh: "固定版本的分词器把文本转成词元 ID；按来源、按阶段设定的配比权重（例如 Megatron-LM 读取的带权前缀列表）决定每个来源贡献多少词元。" },
    does: { en: "Converts accepted text to token IDs and fixes the sampling weight of each source for each training phase. The mixture is a manifest, not a directory listing.", zh: "把文本转成词元 ID，并为每个训练阶段固定各来源的采样权重。配比是一份清单，而不是一个目录列表。" },
    section: "data",
  },
  {
    id: "shards", layer: "data",
    name: { en: "Shard store and loader", zh: "分片存储与加载器" },
    examples: { en: "object storage or a parallel file system; streaming loaders", zh: "对象存储或并行文件系统；流式加载器" },
    more: { en: "Immutable token shards on object storage or a parallel file system such as Lustre, read by streaming loaders such as MosaicML Streaming or Megatron's indexed datasets.", zh: "放在对象存储或 Lustre 这类并行文件系统上的不可变词元分片，由 MosaicML Streaming 或 Megatron 索引数据集这类流式加载器读取。" },
    does: { en: "Holds content-addressed token shards and streams batches to every data-parallel rank in a deterministic order, so a restart resumes at the exact sample.", zh: "保存按内容寻址的词元分片，以确定的顺序把批次流式发给每个数据并行进程，重启后可以从确切的样本处继续。" },
    section: "data",
  },
  {
    id: "ptdata", layer: "data",
    name: { en: "Post-training data", zh: "后训练数据" },
    examples: { en: "demonstrations, preference pairs, RL tasks with checkers", zh: "示范数据、偏好对、带检查器的强化学习任务" },
    more: { en: "Demonstrations written by people or generated by a teacher, preference pairs from annotators or AI feedback, and RL task sets whose items carry a checker, a test suite, or an environment image.", zh: "人工撰写或教师模型生成的示范数据，来自标注员或 AI 反馈的偏好对，以及每道题都附带检查器、测试集或环境镜像的强化学习任务集。" },
    does: { en: "Supplies the later stages: demonstrations for SFT, comparisons for preference optimization, and tasks with checkable outcomes for RL, with the same lineage as pretraining sources.", zh: "供给后续阶段：SFT 用示范数据，偏好优化用比较数据，强化学习用结果可检查的任务；谱系要求与预训练来源相同。" },
    section: "data",
  },
  {
    id: "trainer", layer: "runtime",
    name: { en: "Training runtime", zh: "训练运行时" },
    examples: { en: "Megatron Core, TorchTitan, DeepSpeed, MaxText; the learner of an RL framework", zh: "Megatron Core、TorchTitan、DeepSpeed、MaxText；强化学习框架中的学习器" },
    more: { en: "Megatron Core, TorchTitan, DeepSpeed, or MaxText, with a layout over data, tensor, pipeline, context, and expert parallelism. In RL, a framework such as verl, OpenRLHF, NeMo RL, slime, prime-rl, SkyRL, or AReaL drives the same kind of runtime as its learner.", zh: "Megatron Core、TorchTitan、DeepSpeed 或 MaxText，按数据、张量、流水线、上下文和专家几个维度做并行布局。强化学习中，verl、OpenRLHF、NeMo RL、slime、prime-rl、SkyRL、AReaL 等框架把同类运行时当作学习器来驱动。" },
    does: { en: "Runs the optimizer step on a gang of accelerators under a parallelism layout. Every stage uses it: pretraining, mid-training, SFT, preference training, and the learner of an RL run.", zh: "在一组加速器上按并行布局执行优化器步骤。每个阶段都用它：预训练、中期训练、SFT、偏好训练，以及强化学习中的学习器。" },
    section: "job",
  },
  {
    id: "ckpt", layer: "runtime",
    name: { en: "Checkpoint store", zh: "检查点存储" },
    examples: { en: "sharded, asynchronous saves; fast and durable tiers", zh: "分片异步保存；快速层与持久层" },
    more: { en: "PyTorch Distributed Checkpoint, Megatron's torch_dist format, or Orbax for JAX, saved asynchronously to a fast tier and a durable tier with a retention schedule.", zh: "PyTorch Distributed Checkpoint、Megatron 的 torch_dist 格式，或 JAX 的 Orbax；异步写入快速层和持久层，并按保留计划清理。" },
    does: { en: "Writes sharded model and optimizer state with a short pause in training, and restores the run after a failure, on the same parallel layout or a different one.", zh: "只让训练短暂停顿就写出分片的模型和优化器状态；故障之后恢复训练，可以用原来的并行布局，也可以换一种。" },
    section: "ckpt",
  },
  {
    id: "tracking", layer: "runtime",
    name: { en: "Experiment tracking", zh: "实验追踪" },
    examples: { en: "Weights & Biases, MLflow, TensorBoard", zh: "Weights & Biases、MLflow、TensorBoard" },
    more: { en: "Weights & Biases, MLflow, or TensorBoard logs keyed by run identity; the same store holds the evaluation scores of each checkpoint.", zh: "按运行标识索引的 Weights & Biases、MLflow 或 TensorBoard 日志；同一处还保存每个检查点的评测分数。" },
    does: { en: "Records each run's identity, configuration, and metrics, such as loss, throughput, MFU, and rollout statistics, so every number traces back to the run that produced it.", zh: "记录每次运行的标识、配置和指标，例如损失、吞吐、MFU 和轨迹统计，让每个数字都能追溯到产生它的那次运行。" },
    section: "job",
  },
  {
    id: "rollout", layer: "rl",
    name: { en: "Rollout engines", zh: "轨迹生成引擎" },
    examples: { en: "vLLM, SGLang", zh: "vLLM、SGLang" },
    more: { en: "vLLM or SGLang replicas that generate with the current policy, return token IDs and log-probabilities, and take new weights over NCCL, CUDA IPC, or disk.", zh: "用当前策略生成的 vLLM 或 SGLang 副本，返回词元 ID 和对数概率，通过 NCCL、CUDA IPC 或磁盘接收新权重。" },
    does: { en: "Generate trajectories with the current policy. They are serving engines inside the training job: batched and cache-aware, and paused or updated in place when new weights arrive.", zh: "用当前策略生成轨迹。它们是训练任务里的推理服务引擎：批处理、复用缓存，新权重到达时暂停或原地更新。" },
    section: "rollout",
  },
  {
    id: "reward", layer: "rl",
    name: { en: "Rewards and verifiers", zh: "奖励与验证器" },
    examples: { en: "rule checkers, test runners, reward models, model judges", zh: "规则检查器、测试运行器、奖励模型、模型裁判" },
    more: { en: "Rule-based checkers such as Math-Verify, test runs inside the sandbox, reward-model servers, and model judges served by the same kind of engine as the rollouts.", zh: "Math-Verify 这类规则检查器、在沙箱里执行的测试、奖励模型服务，以及由与轨迹生成同类的引擎提供服务的模型裁判。" },
    does: { en: "Scores finished trajectories with a deterministic checker, a test run, a learned reward model, or a model judge. It runs outside the policy's writable boundary and versions its own code.", zh: "用确定性检查器、测试运行、学到的奖励模型或模型裁判，为已完成的轨迹打分。它运行在策略可写范围之外，自身代码也有版本。" },
    section: "env",
  },
  {
    id: "envs", layer: "rl",
    name: { en: "Environment fleet", zh: "环境集群" },
    examples: { en: "sandboxed code, tool, and browser environments on CPU nodes", zh: "运行在 CPU 节点上的代码、工具和浏览器沙箱环境" },
    more: { en: "Containers, gVisor, or microVMs on CPU nodes, behind environment interfaces such as OpenEnv, verifiers, or SkyRL-Gym; one live environment for each trajectory in flight.", zh: "CPU 节点上的容器、gVisor 或 microVM，前面是 OpenEnv、verifiers、SkyRL-Gym 这类环境接口；每条进行中的轨迹对应一个活着的环境。" },
    does: { en: "Runs one isolated environment per trajectory in flight, such as a repository with its tests, a tool server, or a browser. It resets to a pinned image, executes the policy's actions, and returns observations.", zh: "每条进行中的轨迹都有一个隔离环境，例如带测试的代码仓库、工具服务或浏览器。环境从固定镜像重置，执行策略给出的动作，并返回观察结果。" },
    section: "env",
  },
  {
    id: "gate", layer: "gates",
    name: { en: "Evaluation gate", zh: "评测关卡" },
    examples: { en: "lm-evaluation-harness, Inspect; held-out suites", zh: "lm-evaluation-harness、Inspect；留出评测集" },
    more: { en: "lm-evaluation-harness or Inspect against a candidate served behind an OpenAI-compatible endpoint: capability, regression, safety, and contamination checks against thresholds fixed before the run.", zh: "用 lm-evaluation-harness 或 Inspect 评测部署在 OpenAI 兼容端点后的候选模型：能力、回归、安全和污染检查，阈值在运行前就已确定。" },
    does: { en: "Scores candidate checkpoints on held-out suites and compares them with the baseline under a rule fixed before the run. A candidate that fails does not reach release.", zh: "在留出评测集上为候选检查点打分，并按运行前定好的规则与基线比较。不通过的候选到不了发布环节。" },
    section: "gate",
  },
  {
    id: "release", layer: "gates",
    name: { en: "Release", zh: "发布" },
    examples: { en: "safetensors, card, license, signature", zh: "safetensors、模型卡、许可证、签名" },
    more: { en: "Weights converted to safetensors with the tokenizer, chat template, and generation defaults; a model card and license; a signature under the OpenSSF model signing specification; published to a model hub or an OCI registry.", zh: "转换成 safetensors 的权重，连同分词器、对话模板和生成默认值；模型卡和许可证；按 OpenSSF 模型签名规范做的签名；发布到模型仓库或 OCI 镜像仓库。" },
    does: { en: "Converts the gated checkpoint into a serving artifact, checks that it loads and reproduces the evaluated outputs, signs it, and hands it to serving with its card and license.", zh: "把通过关卡的检查点转换成推理服务用的产物，检查它能加载且能复现评测时的输出，签名后连同模型卡和许可证交给推理服务。" },
    section: "release",
  },
  {
    id: "scheduler", layer: "compute",
    name: { en: "Scheduler", zh: "调度器" },
    examples: { en: "Slurm; Kubernetes with Kueue and JobSet", zh: "Slurm；带 Kueue 和 JobSet 的 Kubernetes" },
    more: { en: "Slurm, or Kubernetes with Kueue queues and quotas over JobSet workloads, admitted all at once with topology-aware placement.", zh: "Slurm，或 Kubernetes 上的 Kueue 队列与配额，管理 JobSet 工作负载，整体一次准入，并按拓扑放置。" },
    does: { en: "Admits a job's workers all together or not at all, places them close together in the network, restarts the whole gang after a failure, and places the rollout engines and the environment fleet.", zh: "让一个任务的全部工作进程要么一起准入、要么都不准入，把它们放在网络上相近的位置，故障后整组重启；轨迹生成引擎和环境集群也由它放置。" },
    section: "job",
  },
  {
    id: "accel", layer: "compute",
    name: { en: "Accelerators and fabric", zh: "加速器与互连" },
    examples: { en: "GPU or TPU nodes; NVLink, InfiniBand or RoCE; CPU nodes", zh: "GPU 或 TPU 节点；NVLink、InfiniBand 或 RoCE；CPU 节点" },
    more: { en: "GPU servers joined by NVLink inside a node or rack and by InfiniBand or RoCE between nodes, TPU slices with their own interconnect, and CPU nodes for the environment fleet.", zh: "节点或机柜内部用 NVLink 连接、节点之间用 InfiniBand 或 RoCE 连接的 GPU 服务器，自带互连的 TPU 切片，以及承载环境集群的 CPU 节点。" },
    does: { en: "The accelerators and the network between them, which set step time, the bandwidth available to each parallelism dimension, and how much of the job one failure stops.", zh: "加速器以及它们之间的网络，决定了每一步的耗时、每个并行维度能用的带宽，以及一次故障会让多大一部分任务停下。" },
    section: "job",
  },
];
const byId = new Map(COMPS.map((c) => [c.id, c]));

interface Hop { from: Id; to: Id | "out"; call: Text; kind: Kind }
const HOPS: readonly Hop[] = [
  { from: "sources", to: "process", kind: "data", call: { en: "raw documents with source and license IDs", zh: "带来源和许可证标识的原始文档" } },
  { from: "process", to: "tokenize", kind: "data", call: { en: "accepted text", zh: "被接受的文本" } },
  { from: "tokenize", to: "shards", kind: "data", call: { en: "token shards and the mixture manifest", zh: "词元分片与配比清单" } },
  { from: "shards", to: "trainer", kind: "data", call: { en: "batches in a resumable order", zh: "顺序可恢复的批次" } },
  { from: "ptdata", to: "trainer", kind: "data", call: { en: "SFT examples, preference pairs, RL tasks", zh: "SFT 样本、偏好对、强化学习任务" } },
  { from: "trainer", to: "ckpt", kind: "weights", call: { en: "sharded model and optimizer state", zh: "分片的模型与优化器状态" } },
  { from: "ckpt", to: "trainer", kind: "weights", call: { en: "restore after a failure", zh: "故障后恢复" } },
  { from: "trainer", to: "tracking", kind: "evidence", call: { en: "loss, throughput, MFU, run identity", zh: "损失、吞吐、MFU、运行标识" } },
  { from: "trainer", to: "rollout", kind: "weights", call: { en: "new policy weights over NCCL, IPC, or disk", zh: "经 NCCL、IPC 或磁盘传送的新策略权重" } },
  { from: "rollout", to: "envs", kind: "rollouts", call: { en: "actions: tool calls, code, commands", zh: "动作：工具调用、代码、命令" } },
  { from: "envs", to: "rollout", kind: "rollouts", call: { en: "observations", zh: "观察结果" } },
  { from: "rollout", to: "reward", kind: "rollouts", call: { en: "finished trajectories with token IDs and log-probabilities", zh: "带词元 ID 和对数概率的完整轨迹" } },
  { from: "envs", to: "reward", kind: "rollouts", call: { en: "final environment state", zh: "环境的最终状态" } },
  { from: "reward", to: "trainer", kind: "rollouts", call: { en: "scored trajectories", zh: "打过分的轨迹" } },
  { from: "ckpt", to: "gate", kind: "weights", call: { en: "candidate checkpoints", zh: "候选检查点" } },
  { from: "gate", to: "tracking", kind: "evidence", call: { en: "scores for each checkpoint", zh: "每个检查点的分数" } },
  { from: "gate", to: "release", kind: "evidence", call: { en: "a passed candidate with its report", zh: "通过的候选及其报告" } },
  { from: "release", to: "out", kind: "weights", call: { en: "signed artifact for serving", zh: "交给推理服务的已签名产物" } },
];

const KIND_ORDER: readonly Kind[] = ["data", "weights", "rollouts", "evidence"];
const KIND_COLOR: Record<Kind, string> = { data: C.c1, weights: C.c2, rollouts: C.c3, evidence: C.c4 };
const KINDS: Record<Kind, Text> = {
  data: { en: "data", zh: "数据" },
  weights: { en: "weights and checkpoints", zh: "权重与检查点" },
  rollouts: { en: "trajectories and rewards", zh: "轨迹与奖励" },
  evidence: { en: "metrics and evaluation results", zh: "指标与评测结果" },
};

const LAYERS: Record<Layer, Text> = {
  data: { en: "Data plane", zh: "数据平面" },
  runtime: { en: "Training runtime", zh: "训练运行时" },
  rl: { en: "RL post-training", zh: "强化学习后训练" },
  gates: { en: "Evaluation and release", zh: "评测与发布" },
  compute: { en: "Compute, under every job above", zh: "算力，承载以上所有任务" },
};

// Each section is a section of the chapter.
const SECTIONS: Record<Section, Text> = {
  data: { en: "the data plane and its lineage record", zh: "数据平面及其谱系记录" },
  job: { en: "the cluster and the job, with the run identity", zh: "集群与任务，以及运行标识" },
  ckpt: { en: "the checkpoint store and its failure budget", zh: "检查点存储及其故障预算" },
  rollout: { en: "the rollout fleet", zh: "轨迹生成集群" },
  env: { en: "environments and verifiers", zh: "环境与验证器" },
  gate: { en: "the evaluation gate and its promotion rule", zh: "评测关卡及其晋级规则" },
  release: { en: "the release artifact", zh: "发布产物" },
};

// ---------------------------------------------------------------- labels

const labels = {
  en: {
    title: "A reference training stack by layer, with what each hand-off carries",
    all: "What each hand-off carries",
    hint: "Select a component to see what it does, example choices, and the section of this chapter that covers it.",
    examplesHead: "Examples",
    covered: "Covered in {c}.",
    callsOut: "Hands off",
    callsIn: "Receives",
    hopOut: "to {to}: {call}",
    hopIn: "from {from}: {call}",
    out: "serving",
    outLabel: "to serving",
    legend: "Arrow color is what the hand-off carries",
    legendPhone: "Swatch color is what the hand-off carries",
    kindLine: "{kind}: {list}",
    hopShort: "{from} to {to}",
    listSep: "; ",
    phoneOut: "to {to}: {kind}",
    describeAll: "A training stack of {n} components in {l} layers. Data flows one way into the training runtime; weights leave it for the checkpoint store, the rollout engines, and, through the evaluation gate, release; trajectories return to it only through the rewards and verifiers.",
    describeOne: "{name}, in the {layer} layer. {does} Covered in {c}.",
  },
  zh: {
    title: "按层划分的参考训练技术栈，以及每次交接传递的内容",
    all: "每次交接传递什么",
    hint: "选中一个组件，可以查看它的作用、可选的实现，以及本章哪一节讲它。",
    examplesHead: "实现示例",
    covered: "详见{c}一节。",
    callsOut: "交给",
    callsIn: "接收",
    hopOut: "到{to}：{call}",
    hopIn: "来自{from}：{call}",
    out: "推理服务",
    outLabel: "交给推理服务",
    legend: "箭头颜色表示交接传递的内容",
    legendPhone: "色块颜色表示交接传递的内容",
    kindLine: "{kind}：{list}",
    hopShort: "{from}到{to}",
    listSep: "；",
    phoneOut: "到{to}：{kind}",
    describeAll: "一套由 {n} 个组件、{l} 层组成的训练技术栈。数据单向流入训练运行时；权重从训练运行时流向三处：检查点存储、轨迹生成引擎，以及经评测关卡到达的发布环节；轨迹只能经由奖励与验证器回到训练运行时。",
    describeOne: "{name}，属于{layer}层。{does}详见{c}一节。",
  },
};

type Sel = "all" | Id;
type P = { component: Sel };

const nameOf = (id: Id | "out", lang: Lang) => (id === "out" ? labels[lang].out : byId.get(id)!.name[lang]);
// In Chinese text a Latin word next to a CJK glyph takes a space on that side.
const latinEdge = /[A-Za-z0-9)]/;
const lead = (s: string, lang: Lang) => (lang === "zh" && latinEdge.test(s[0]) ? ` ${s}` : s);
const tail = (s: string, lang: Lang) => (lang === "zh" && latinEdge.test(s[s.length - 1]) ? `${s} ` : s);
const touches = (h: Hop, id: Id) => h.from === id || h.to === id;

function describe(st: State<P>, lang: Lang): string {
  const L = labels[lang];
  const sel = st.p.component;
  if (sel === "all") return tpl(L.describeAll, { n: COMPS.length, l: Object.keys(LAYERS).length });
  const c = byId.get(sel)!;
  return tpl(L.describeOne, { name: c.name[lang], layer: LAYERS[c.layer][lang], does: c.does[lang], c: SECTIONS[c.section][lang] });
}

// ---------------------------------------------------------------- boxes

interface Box { x0: number; x1: number; y0: number; y1: number; cx: number; cy: number }
type Pt = [number, number];

const PAD = 8;
const NAME = TYPE.label, EX = TYPE.small;
const NAME_LH = NAME + 4, EX_LH = EX + 4;

function boxLines(c: Comp, width: number, lang: Lang) {
  const inner = width - 2 * PAD;
  return { name: wrapLines(c.name[lang], NAME, inner), ex: wrapLines(c.examples[lang], EX, inner) };
}
const boxHeight = (ls: { name: string[]; ex: string[] }) =>
  PAD + ls.name.length * NAME_LH + 2 + ls.ex.length * EX_LH + PAD - 4;

function drawBox(c: Comp, b: Box, lang: Lang, st: { sel: Sel; dim: boolean }, extraLines: string[] = []): string {
  const ls = boxLines(c, b.x1 - b.x0, lang);
  const isSel = st.sel === c.id;
  const parts: string[] = [];
  parts.push(el("rect", { x: b.x0, y: b.y0, width: b.x1 - b.x0, height: b.y1 - b.y0, rx: 6, fill: C.paper, stroke: isSel ? C.ink : C.rule, "stroke-width": isSel ? 2 : 1 }));
  let y = b.y0 + PAD + NAME - 1;
  for (const ln of ls.name) { parts.push(text(b.x0 + PAD, y, ln, { "font-size": NAME, class: "fig-t-strong" })); y += NAME_LH; }
  y += 2 - (NAME_LH - EX_LH) - 1;
  for (const ln of ls.ex) { parts.push(text(b.x0 + PAD, y, ln, { "font-size": EX, class: "fig-t-muted" })); y += EX_LH; }
  if (extraLines.length) parts.push(...extraLines);
  return g({ opacity: st.dim ? 0.5 : undefined, "data-fig-set": `component=${c.id}`, class: "fig-hit" }, ...parts);
}

function arrowHead(pts: Pt[], color: string): string {
  const [x1, y1] = pts[pts.length - 1];
  const [x0, y0] = pts[pts.length - 2];
  const len = Math.hypot(x1 - x0, y1 - y0) || 1;
  const ux = (x1 - x0) / len, uy = (y1 - y0) / len;
  const s = 7, hw = 4;
  const bx = x1 - ux * s, by = y1 - uy * s;
  return el("path", { d: `M${x1},${y1}L${bx - uy * hw},${by + ux * hw}L${bx + uy * hw},${by - ux * hw}Z`, fill: color });
}

function trimmed(pts: Pt[], by = 6): Pt[] {
  const out = pts.map((p) => [...p] as Pt);
  const n = out.length;
  const [x1, y1] = out[n - 1], [x0, y0] = out[n - 2];
  const len = Math.hypot(x1 - x0, y1 - y0) || 1;
  out[n - 1] = [x1 - ((x1 - x0) / len) * by, y1 - ((y1 - y0) / len) * by];
  return out;
}

const pathOf = (pts: Pt[]) => pts.map(([x, y], i) => `${i ? "L" : "M"}${Math.round(x * 10) / 10},${Math.round(y * 10) / 10}`).join("");

function edge(pts: Pt[], color: string, on: boolean, dim: boolean): string {
  return g({ opacity: dim ? 0.22 : undefined },
    el("path", { d: pathOf(trimmed(pts)), fill: "none", stroke: color, "stroke-width": on ? 2.8 : 1.8, "stroke-linejoin": "round" }),
    arrowHead(pts, color));
}

// ---------------------------------------------------------------- desktop layout

// Four columns inside groups that span the width between margins. Rows from the
// top: the data plane (the four pipeline stages, then post-training data under
// the first two); the training runtime (checkpoint store over experiment
// tracking in the first column, the trainer across the other three); the RL
// group across the last three columns (rollout engines beside the rewards and
// verifiers, the environment fleet under both); the evaluation gate and
// release; compute. The left margin carries candidate checkpoints down to the
// gate, and the gate's scores rise through the empty first column of the RL
// row into the tracker. Group captions sit on the side no arrow enters from.
const M = 20, GUT = 18, GAP = 28, CAP = 20, INSET = 8, INNER = 20, STACK = 12;

interface Group { layer: Layer; x0: number; x1: number; y0: number; y1: number; right: boolean }

function desktop(w: number, lang: Lang) {
  const X0 = M + INSET, X1 = w - M - INSET;
  const colW = (X1 - X0 - 3 * GUT) / 4;
  const col = (i: number): [number, number] => [X0 + i * (colW + GUT), X0 + i * (colW + GUT) + colW];
  const span = (a: number, b: number): [number, number] => [col(a)[0], col(b)[1]];
  const B = new Map<Id, Box>();
  const groups: Group[] = [];
  const put = (id: Id, x0: number, x1: number, y0: number, h: number) =>
    B.set(id, { x0, x1, y0, y1: y0 + h, cx: (x0 + x1) / 2, cy: y0 + h / 2 });
  const hOf = (id: Id, width: number) => boxHeight(boxLines(byId.get(id)!, width, lang));
  const row = (ids: Array<[Id, [number, number]]>, y: number) => {
    const h = Math.max(...ids.map(([id, [x0, x1]]) => hOf(id, x1 - x0)));
    for (const [id, [x0, x1]] of ids) put(id, x0, x1, y, h);
    return h;
  };
  let y = 0;
  // Data plane.
  const dTop = y;
  const hA = row([["sources", col(0)], ["process", col(1)], ["tokenize", col(2)], ["shards", col(3)]], dTop + CAP);
  const yA2 = dTop + CAP + hA + INNER;
  const hA2 = row([["ptdata", span(0, 1)]], yA2);
  const dBot = yA2 + hA2 + INSET;
  groups.push({ layer: "data", x0: M, x1: w - M, y0: dTop, y1: dBot, right: false });
  // Training runtime: the checkpoint store over the tracker, the trainer beside both.
  const rTop = dBot + GAP;
  const yB = rTop + CAP;
  const hCk = hOf("ckpt", colW), hTr = hOf("tracking", colW);
  const leftH = hCk + STACK + hTr;
  const hT = Math.max(leftH, hOf("trainer", span(1, 3)[1] - span(1, 3)[0]));
  put("ckpt", col(0)[0], col(0)[1], yB, hCk + (hT - leftH) / 2);
  put("tracking", col(0)[0], col(0)[1], B.get("ckpt")!.y1 + STACK, hTr + (hT - leftH) / 2);
  put("trainer", span(1, 3)[0], span(1, 3)[1], yB, hT);
  const rBot = yB + hT + INSET;
  groups.push({ layer: "runtime", x0: M, x1: w - M, y0: rTop, y1: rBot, right: false });
  // RL post-training, over the last three columns.
  const lTop = rBot + GAP;
  const hC1 = row([["rollout", col(1)], ["reward", span(2, 3)]], lTop + CAP);
  const yC2 = lTop + CAP + hC1 + INNER;
  const hC2 = row([["envs", span(1, 3)]], yC2);
  const lBot = yC2 + hC2 + INSET;
  groups.push({ layer: "rl", x0: col(1)[0] - INSET, x1: w - M, y0: lTop, y1: lBot, right: true });
  // Evaluation and release.
  const eTop = lBot + GAP;
  row([["gate", col(0)], ["release", span(1, 2)]], eTop + CAP);
  const eBot = B.get("gate")!.y1 + INSET;
  groups.push({ layer: "gates", x0: M, x1: w - M, y0: eTop, y1: eBot, right: true });
  // Compute.
  const cTop = eBot + GAP;
  row([["scheduler", span(0, 1)], ["accel", span(2, 3)]], cTop + CAP);
  const cBot = B.get("scheduler")!.y1 + INSET;
  groups.push({ layer: "compute", x0: M, x1: w - M, y0: cTop, y1: cBot, right: false });
  return { B, groups, height: cBot, col };
}

function desktopRoute(h: Hop, lay: ReturnType<typeof desktop>, w: number): Pt[] {
  const { B, col } = lay;
  const a = B.get(h.from)!;
  if (h.to === "out") return [[a.x1, a.cy], [w - 2, a.cy]];
  const b = B.get(h.to)!;
  switch (`${h.from}>${h.to}`) {
    case "sources>process": case "process>tokenize": case "tokenize>shards": case "rollout>reward": case "gate>release":
      return [[a.x1, a.cy], [b.x0, a.cy]];
    case "shards>trainer": return [[a.cx, a.y1], [a.cx, b.y0]];
    case "ptdata>trainer": { const x = col(1)[0] + (col(1)[1] - col(1)[0]) / 2; return [[x, a.y1], [x, b.y0]]; }
    case "trainer>ckpt": return [[a.x0, b.cy - 5], [b.x1, b.cy - 5]];
    case "ckpt>trainer": return [[a.x1, a.cy + 5], [b.x0, a.cy + 5]];
    case "trainer>tracking": return [[a.x0, b.cy], [b.x1, b.cy]];
    case "trainer>rollout": return [[b.cx, a.y1], [b.cx, b.y0]];
    case "rollout>envs": return [[a.cx - 6, a.y1], [a.cx - 6, b.y0]];
    case "envs>rollout": return [[b.cx + 6, a.y0], [b.cx + 6, b.y1]];
    case "envs>reward": return [[b.cx, a.y0], [b.cx, b.y1]];
    case "reward>trainer": return [[a.cx, a.y0], [a.cx, b.y1]];
    case "ckpt>gate": return [[a.x0, a.cy], [M / 2, a.cy], [M / 2, b.cy], [b.x0, b.cy]];
    case "gate>tracking": return [[a.cx, a.y0], [a.cx, b.y1]];
  }
  return [[b.cx, a.y1], [b.cx, b.y0]];
}

// ---------------------------------------------------------------- phone layout

// One column, top to bottom in layer order. Each box lists its outgoing
// hand-offs under its examples, with the swatch of what each one carries.
const LAYER_ORDER: readonly Layer[] = ["data", "runtime", "rl", "gates", "compute"];
const HOP_SIZE = TYPE.small, HOP_LH = HOP_SIZE + 5, SW = 16;

function phoneHops(c: Comp, x0: number, width: number, lang: Lang) {
  const L = labels[lang];
  const rows: Array<{ lines: string[]; color: string }> = [];
  for (const h of HOPS.filter((h) => h.from === c.id)) {
    rows.push({ lines: wrapLines(tpl(L.phoneOut, { to: lead(nameOf(h.to, lang), lang), kind: KINDS[h.kind][lang] }), HOP_SIZE, width - 2 * PAD - SW - 6), color: KIND_COLOR[h.kind] });
  }
  const n = rows.reduce((s, r) => s + r.lines.length, 0);
  const draw = (yStart: number): string[] => {
    const out: string[] = [];
    let yy = yStart;
    for (const r of rows) {
      out.push(el("line", { x1: x0 + PAD, x2: x0 + PAD + SW, y1: yy - 4, y2: yy - 4, stroke: r.color, "stroke-width": 2.4 }));
      for (const ln of r.lines) { out.push(text(x0 + PAD + SW + 6, yy, ln, { "font-size": HOP_SIZE })); yy += HOP_LH; }
    }
    return out;
  };
  return { height: n ? n * HOP_LH + 4 : 0, draw };
}

function phone(w: number, lang: Lang, sel: Sel, dimBox: (id: Id) => boolean): { svg: string; h: number } {
  const parts: string[] = [];
  let y = 0;
  for (const layer of LAYER_ORDER) {
    const comps = COMPS.filter((c) => c.layer === layer);
    const x0 = INSET, x1 = w - INSET;
    const top = y;
    let yy = y + CAP;
    const inner: string[] = [];
    comps.forEach((c, i) => {
      const ls = boxLines(c, x1 - x0, lang);
      const hops = phoneHops(c, x0, x1 - x0, lang);
      const base = boxHeight(ls);
      const h = base + hops.height;
      const b: Box = { x0, x1, y0: yy, y1: yy + h, cx: (x0 + x1) / 2, cy: yy + h / 2 };
      inner.push(drawBox(c, b, lang, { sel, dim: dimBox(c.id) }, hops.draw(yy + base + HOP_SIZE - 2)));
      yy += h + (i < comps.length - 1 ? 8 : 0);
    });
    yy += INSET;
    parts.push(el("rect", { x: 0, y: top, width: w, height: yy - top, rx: 8, fill: C.panel }));
    parts.push(text(INSET, top + 14, LAYERS[layer][lang], { "font-size": TYPE.small, class: "fig-t-muted" }));
    parts.push(...inner);
    y = yy + 10;
  }
  return { svg: g({ class: "fig-stack" }, ...parts), h: y - 10 };
}

// ---------------------------------------------------------------- legend and readout

function drawLegend(y0: number, w: number, lang: Lang, narrow: boolean): { svg: string; h: number } {
  const L = labels[lang];
  const fs = TYPE.small;
  const parts: string[] = [text(0, y0 + fs, narrow ? L.legendPhone : L.legend, { "font-size": fs, class: "fig-t-muted" })];
  let y = y0 + fs + 16, x = 0;
  for (const k of KIND_ORDER) {
    const label = KINDS[k][lang];
    const iw = SW + 6 + textWidth(label, fs);
    if (x > 0 && x + iw > w) { x = 0; y += fs + 8; }
    parts.push(el("line", { x1: x, x2: x + SW, y1: y - 4, y2: y - 4, stroke: KIND_COLOR[k], "stroke-width": 2.4 }));
    parts.push(text(x + SW + 6, y, label, { "font-size": fs }));
    x += iw + 16;
  }
  return { svg: g({ class: "fig-legend" }, ...parts), h: y - y0 + 6 };
}

function drawReadout(sel: Sel, y0: number, w: number, lang: Lang, narrow: boolean): { svg: string; h: number } {
  const L = labels[lang];
  const parts: string[] = [];
  const fs = TYPE.body, lh = fs + 6;
  let y = y0;
  const para = (s: string, cls?: string, indent = 0) => {
    for (const ln of wrapLines(s, fs, w - indent)) { parts.push(text(indent, y + fs, ln, { "font-size": fs, class: cls })); y += lh; }
  };
  const swatchPara = (s: string, color: string) => {
    parts.push(el("line", { x1: 0, x2: SW, y1: y + fs - 4, y2: y + fs - 4, stroke: color, "stroke-width": 2.4 }));
    para(s, undefined, SW + 8);
    y += 2;
  };
  parts.push(el("line", { x1: 0, x2: w, y1: y, y2: y, stroke: C.grid }));
  y += 10;
  if (sel === "all") {
    if (!narrow) {
      parts.push(text(0, y + TYPE.label, L.all, { "font-size": TYPE.label, class: "fig-t-strong" }));
      y += TYPE.label + 10;
      for (const k of KIND_ORDER) {
        const list = HOPS.filter((h) => h.kind === k)
          .map((h) => tpl(L.hopShort, { from: tail(nameOf(h.from, lang), lang), to: lead(nameOf(h.to, lang), lang) }))
          .join(L.listSep);
        swatchPara(tpl(L.kindLine, { kind: KINDS[k][lang], list }), KIND_COLOR[k]);
      }
      y += 4;
    }
    para(L.hint, "fig-t-muted");
    return { svg: g({ class: "fig-readout" }, ...parts), h: y - y0 };
  }
  const c = byId.get(sel)!;
  parts.push(text(0, y + TYPE.label, c.name[lang], { "font-size": TYPE.label, class: "fig-t-strong" }));
  const tw = textWidth(c.name[lang], TYPE.label);
  if (tw + 10 + textWidth(LAYERS[c.layer][lang], TYPE.small) <= w) {
    parts.push(text(tw + 10, y + TYPE.label, LAYERS[c.layer][lang], { "font-size": TYPE.small, class: "fig-t-muted" }));
  }
  y += TYPE.label + 10;
  para(c.does[lang]);
  y += 4;
  parts.push(text(0, y + TYPE.small, L.examplesHead, { "font-size": TYPE.small, class: "fig-t-muted" }));
  y += TYPE.small + 8;
  para(c.more[lang]);
  y += 4;
  para(tpl(L.covered, { c: SECTIONS[c.section][lang] }));
  y += 6;
  const out = HOPS.filter((h) => h.from === c.id), inn = HOPS.filter((h) => h.to === c.id);
  for (const [head, hs, tmpl] of [[L.callsOut, out, L.hopOut], [L.callsIn, inn, L.hopIn]] as const) {
    if (!hs.length) continue;
    parts.push(text(0, y + TYPE.small, head, { "font-size": TYPE.small, class: "fig-t-muted" }));
    y += TYPE.small + 8;
    for (const h of hs) {
      swatchPara(tpl(tmpl, { to: lead(nameOf(h.to, lang), lang), from: lead(nameOf(h.from, lang), lang), call: h.call[lang] }), KIND_COLOR[h.kind]);
    }
    y += 4;
  }
  return { svg: g({ class: "fig-readout" }, ...parts), h: y - y0 };
}

// ---------------------------------------------------------------- render

function render(st: State<P>, lang: Lang): string {
  const L = labels[lang];
  const w = st.w;
  const sel = st.p.component;
  const narrow = w < 480;
  const related = new Set<Id>();
  if (sel !== "all") {
    related.add(sel);
    for (const h of HOPS) if (touches(h, sel)) { related.add(h.from); if (h.to !== "out") related.add(h.to); }
  }
  const dimBox = (id: Id) => sel !== "all" && !related.has(id);
  const parts: string[] = [];
  let y: number;
  if (narrow) {
    const ph = phone(w, lang, sel, dimBox);
    parts.push(ph.svg);
    y = ph.h + 16;
  } else {
    const lay = desktop(w, lang);
    for (const gr of lay.groups) {
      parts.push(el("rect", { x: gr.x0, y: gr.y0, width: gr.x1 - gr.x0, height: gr.y1 - gr.y0, rx: 8, fill: C.panel }));
      const cap = LAYERS[gr.layer][lang];
      parts.push(gr.right
        ? text(gr.x1 - INSET, gr.y0 + 14, cap, { "font-size": TYPE.small, class: "fig-t-muted", "text-anchor": "end" })
        : text(gr.x0 + INSET, gr.y0 + 14, cap, { "font-size": TYPE.small, class: "fig-t-muted" }));
    }
    // Hand-offs, the selected component's drawn last.
    const order = [...HOPS].sort((a, b) => Number(sel !== "all" && touches(a, sel)) - Number(sel !== "all" && touches(b, sel)));
    for (const h of order) {
      const on = sel !== "all" && touches(h, sel);
      parts.push(edge(desktopRoute(h, lay, w), KIND_COLOR[h.kind], on, sel !== "all" && !on));
    }
    for (const c of COMPS) parts.push(drawBox(c, lay.B.get(c.id)!, lang, { sel, dim: dimBox(c.id) }));
    const rel = lay.B.get("release")!;
    const outDim = sel !== "all" && sel !== "release";
    parts.push(text(w - M - INSET, rel.cy - 8, L.outLabel, { "font-size": TYPE.small, class: "fig-t-muted fig-t-halo", "text-anchor": "end", opacity: outDim ? 0.5 : undefined }));
    y = lay.height + 18;
  }
  const lg = drawLegend(y, w, lang, narrow);
  parts.push(lg.svg);
  y += lg.h + 12;
  const ro = drawReadout(sel, y, w, lang, narrow);
  parts.push(ro.svg);
  y += ro.h + 4;
  return svg(w, y, describe(st, lang), ...parts);
}

export default defineFigure({
  name: "training-stack",
  title: { en: labels.en.title, zh: labels.zh.title },
  labels,
  params: {
    component: {
      kind: "choice", control: "select", label: { en: "Component", zh: "组件" }, default: "all",
      options: [
        { value: "all", label: { en: "whole stack: what each hand-off carries", zh: "整套技术栈：每次交接传递什么" } },
        ...COMPS.map((c) => ({ value: c.id, label: { en: c.name.en, zh: c.name.zh } })),
      ],
    },
  },
  render,
  describe,
});
