apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aaai-web
  namespace: latere
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - aaai.latere.ai
      secretName: aaai-web-tls
  rules:
    - host: aaai.latere.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aaai-web
                port:
                  number: 80
